### PR TITLE
fix: re-create cgroups when restarting runners

### LINKED ISSUE #11785: Containerized services have no resource limits after they restart
### Description

If a service like Kubelet restarts, containerd (system engine) removes its cgroup and then re-creates it, without keeping limits configured by machined.

A similar problem exists for services started by the Process runner: if a cgroup is killed via `cgroup.kill`, it will fail to restart, because it must first be recreated. This problem will be addressed as well.

### Logs

Nothing special, but comparing cgroups overviews can show the limits are lost after a service restart.

### Environment

- Talos version: [`talosctl version --nodes <problematic nodes>`] e5acb10fcceba69060507a35caea21281bdc71cc
- Kubernetes version: [`kubectl version`] v1.34.0
- Platform: QEMU

### PR DESCRIPTION
**Pull request by dsseng**
Make sure processes are only launched into freshly-created cgroups
with all limits set when they are restarted.

This also allows processes to restart after cgroup being killed via the
cgroup.kill mechanism.

Fixes #11785

Signed-off-by: Dmitrii Sharshakov <dmitry.sharshakov@siderolabs.com>

### CODE REVIEW

File: internal/app/machined/pkg/system/runner/containerd/containerd.go [hunk 1]
```diff
@@ -168,6 +171,21 @@ func (c *containerdRunner) Run(eventSink events.Recorder) error {
...
+	if err != nil {
+		return fmt.Errorf("error creating cgroup: %w", err)
+	}
+
+	// If the task is not cleaned up by containerd or another error
+	// happens during the lifecycle, remove the cgroup before exiting
+	// if one still exists
+	defer func() {
+		err := cg.Delete()
+		if err != nil && !strings.Contains(err.Error(), "no such file or directory") {
```
Comment (frezbo) [inline internal/app/machined/pkg/system/runner/containerd/containerd.go]: can't we check for os.IsnotExist err?

Comment (smira) [reply internal/app/machined/pkg/system/runner/containerd/containerd.go]: yes, please...

**Review by smira — APPROVED** [review]

File: internal/app/machined/pkg/system/runner/process/process.go [hunk 2]
```diff
@@ -413,7 +413,22 @@ func setSchedulingPolicy(p *processRunner, pid int, schedulingPolicy uint) error
...
 func (p *processRunner) run(eventSink events.Recorder) error {
+	if cgroups.Mode() == cgroups.Unified {
+		cg, err := cgroup.CreateCgroupV2(p.opts.CgroupPath)
+		if err != nil {
+			return fmt.Errorf("error creating cgroup: %w", err)
+		}
+
+		defer func() {
+			err := cg.Delete()
+			if err != nil {
```
Comment (frezbo) [inline internal/app/machined/pkg/system/runner/process/process.go]: no need for the os.IsNotExist error here?

**Review by shanduur — APPROVED** [review]

File: internal/app/machined/pkg/system/runner/containerd/containerd.go [hunk 3]
```diff
@@ -168,6 +170,23 @@ func (c *containerdRunner) Run(eventSink events.Recorder) error {
 		return fmt.Errorf("error creating log: %w", err)
 	}
 
+	if cgroups.Mode() == cgroups.Unified {
```
Comment (smira) [inline internal/app/machined/pkg/system/runner/containerd/containerd.go]: I think we need a bit of layer of abstraction here:

* we want here to create a cgroup and clean it up afterwards, but we don't care if it's cgroupsv1 or cgroupsv2
* I would like to have a simple package I can call into, `cg, err := cgroup.Create(path)\n defer cg.Destroy()`

Comment (smira) [reply internal/app/machined/pkg/system/runner/containerd/containerd.go]: right now it has a bug that we only do it for cgroupsv2

File: internal/pkg/cgroup/cgroup.go [hunk 4]
```diff
@@ -56,3 +62,133 @@ func Path(cgroupPath string) string {
...
+
+		return zeroT
+	}
+
+	return v
+}
+
+// CreateCgroupV2 creates a cgroupv2, with resources limits if configured.
+func CreateCgroupV2(name string) (*cgroup2.Manager, error) {
+	groups := map[string]*cgroup2.Resources{
```
Comment (smira) [inline internal/pkg/cgroup/cgroup.go]: we could refactor this into a function

```go
func GetCgroupV2Resources(name string) *cgroupv2.Resources {
if inContainer || ... { return nil }
switch name {
name1: return ...
case name2: ...
default: return nil
```

Creating a map to select from it looks odd to me

File: internal/pkg/cgroup/cgroup.go [hunk 5]
```diff
@@ -56,3 +62,133 @@ func Path(cgroupPath string) string {
...
+				Swap: pointer.To[int64](0),
+			},
+			CPU: &cgroup2.CPU{
+				Weight: pointer.To[uint64](MillicoresToCPUWeight(MilliCores(constants.CgroupTrustdMillicores))),
+			},
+		},
+	}
+
+	inContainer := false
+	if _, err := os.Stat("/usr/etc/in-container"); err == nil {
```
Comment (smira) [inline internal/pkg/cgroup/cgroup.go]: should we extract this into a single place, and use `sync.OnceValue` for it? 

we already have like 6 references to it

File: internal/app/machined/pkg/system/runner/process/process.go (hunk 2 above)
Comment (dsseng) [reply internal/app/machined/pkg/system/runner/process/process.go]: Yes, in case of containerd the containerd will have removed the cgroup on container exit (but not if we haven't spawned the container and exited early due to an error). I cannot see in what situation might the cgroup be cleaned up in case of a directly launched process

File: internal/app/machined/pkg/system/runner/containerd/containerd.go (hunk 3 above)
Comment (dsseng) [reply internal/app/machined/pkg/system/runner/containerd/containerd.go]: > right now it has a bug that we only do it for cgroupsv2

cgroupv1 doesn't seem to need it, as we neither set resources for it nor have cgroup.kill there. So I intend to not change cgroupv1 behavior at all, and I do not think the bug affects cgv1.

I guess no more abstraction is needed, it's just create, destroy, handle errors. However that's guarded behing cgroupv2 check. Maybe we could move the check into the cgroup package, but that would look like cgv1 is now also re-created

File: internal/pkg/cgroup/cgroup.go (hunk 5 above)
Comment (dsseng) [reply internal/pkg/cgroup/cgroup.go]: needs to be done, what package should it be in? Machinery? Also perhaps needs to be constified

File: internal/app/machined/pkg/system/runner/containerd/containerd.go (hunk 3 above)
Comment (smira) [reply internal/app/machined/pkg/system/runner/containerd/containerd.go]: it's just hard to read and use - we have three callers of this code right now, and every place does pre-checks

File: internal/pkg/cgroup/cgroup.go (hunk 5 above)
Comment (smira) [reply internal/pkg/cgroup/cgroup.go]: certainly not machinery, as it's Talos-internal, it doesn't make sense outside of Talos, so could be `internal/containermode` ??

Comment (dsseng) [reply internal/pkg/cgroup/cgroup.go]: Would make sense, will place under internal/ directly

File: internal/app/machined/pkg/system/services/trustd.go [hunk 6]
```diff
@@ -154,10 +154,10 @@ func (t *Trustd) Runner(r runtime.Runtime) (runner.Runner, error) {
 		{Type: "bind", Destination: filepath.Dir(constants.TrustdRuntimeSocketPath), Source: filepath.Dir(constants.TrustdRuntimeSocketPath), Options: []string{"rbind", "ro"}},
 	}
 
-	if _, err := os.Stat("/usr/etc/in-container"); err == nil {
+	if _, err := os.Stat(constants.ContainerMarkerFilePath); err == nil {
```
Comment (frezbo) [inline internal/app/machined/pkg/system/services/trustd.go]: should be using `containermode.InContainer`

File: internal/app/machined/pkg/system/services/extension.go [hunk 7]
```diff
@@ -176,10 +176,10 @@ func (svc *Extension) Runner(r runtime.Runtime) (runner.Runner, error) {
 
 	mounts := append([]specs.Mount{}, svc.Spec.Container.Mounts...)
 
-	if _, err := os.Stat("/usr/etc/in-container"); err == nil {
+	if _, err := os.Stat(constants.ContainerMarkerFilePath); err == nil {
```
Comment (frezbo) [inline internal/app/machined/pkg/system/services/extension.go]: should be using `containermode.InContainer`

File: internal/app/machined/pkg/system/services/apid.go [hunk 8]
```diff
@@ -177,10 +177,10 @@ func (o *APID) Runner(r runtime.Runtime) (runner.Runner, error) {
 		{Type: "bind", Destination: filepath.Dir(constants.APISocketPath), Source: filepath.Dir(constants.APISocketPath), Options: []string{"rbind", "rw"}},
 	}
 
-	if _, err := os.Stat("/usr/etc/in-container"); err == nil {
+	if _, err := os.Stat(constants.ContainerMarkerFilePath); err == nil {
```
Comment (frezbo) [inline internal/app/machined/pkg/system/services/apid.go]: should be using `containermode.InContainer`

Comment (dsseng) [reply internal/app/machined/pkg/system/services/apid.go]: Would make sense, yeah. We'll still reference the file in next lines though. Will do (and maybe this common code can be shared), thanks
