### PR TITLE
Ignore digest part of images when checking version in pre-flight

### LINKED ISSUE #10373: Upgrade fails when using sha digest with images
### Description

When using sha digests with images in machineconfig upgrade fails due to failing semantic version validation. For example, given the following snippet in machineconfig:

```
machine:
  kubelet:
    image: my.registry.mirror/siderolabs/kubelet:v1.31.4@sha256:346676130195670ee7a1005946d1059a22983c32ec8c6a91a2e1bd8d4ac353bd
```

The pre-flight check tries to validate `v1.31.4@sha256:346676130195670ee7a1005946d1059a22983c32ec8c6a91a2e1bd8d4ac353bd` for semantic version syntax, which fails.

### Logs

```
1.2.3.4: user: warning: [2025-02-14T08:09:55.587544745Z]: 2025/02/14 08:09:56 running Talos installer v1.9.3
1.2.3.4: user: warning: [2025-02-14T08:09:55.588748745Z]: 2025/02/14 08:09:56 system disk wipe on upgrade is not supported anymore, option ignored
1.2.3.4: user: warning: [2025-02-14T08:09:55.595250745Z]: 2025/02/14 08:09:56 running pre-flight checks
1.2.3.4: user: warning: [2025-02-14T08:09:55.595963745Z]: 2025/02/14 08:09:56 host Talos version: v1.8.1
1.2.3.4: user: warning: [2025-02-14T08:09:55.597433745Z]: Error: pre-flight checks failed: error parsing kubelet version: Invalid character(s) found in patch number "4@sha256:346676130195670ee7a1005946d1059a22983c32ec8c6a91a2e1bd8d4ac353bd"
1.2.3.4: user: warning: [2025-02-14T08:09:55.598840745Z]: Usage:
1.2.3.4: user: warning: [2025-02-14T08:09:55.598923745Z]:   installer install [flags]
1.2.3.4: user: warning: [2025-02-14T08:09:55.599066745Z]:
1.2.3.4: user: warning: [2025-02-14T08:09:55.599126745Z]: Flags:
1.2.3.4: user: warning: [2025-02-14T08:09:55.599205745Z]:   -h, --help   help for install
1.2.3.4: user: warning: [2025-02-14T08:09:55.599359745Z]:
1.2.3.4: user: warning: [2025-02-14T08:09:55.599419745Z]: Global Flags:
1.2.3.4: user: warning: [2025-02-14T08:09:55.599520745Z]:       --arch string                    The target architecture (default "amd64")
1.2.3.4: user: warning: [2025-02-14T08:09:55.599828745Z]:       --board string                   Deprecated: no op (default "none")
1.2.3.4: user: warning: [2025-02-14T08:09:55.600123745Z]:       --bootloader                     Deprecated: no op (default true)
1.2.3.4: user: warning: [2025-02-14T08:09:55.600397745Z]:       --config string                  The value of talos.config
1.2.3.4: user: warning: [2025-02-14T08:09:55.600649745Z]:       --disk string                    The path to the disk to install to
1.2.3.4: user: warning: [2025-02-14T08:09:55.600929745Z]:       --extra-kernel-arg stringArray   Extra argument to pass to the kernel
1.2.3.4: user: warning: [2025-02-14T08:09:55.601216745Z]:       --force                          Indicates that the install should forcefully format the partition
1.2.3.4: user: warning: [2025-02-14T08:09:55.601593745Z]:       --meta metaValueSlice            A key/value pair for META (default [])
1.2.3.4: user: warning: [2025-02-14T08:09:55.601884745Z]:       --platform string                The value of talos.platform
1.2.3.4: user: warning: [2025-02-14T08:09:55.602154745Z]:       --upgrade                        Indicates that the install is being performed by an upgrade
1.2.3.4: user: warning: [2025-02-14T08:09:55.602524745Z]:       --zero                           Indicates that the install should write zeros to the disk before installing
1.2.3.4: user: warning: [2025-02-14T08:09:55.602928745Z]:
1.2.3.4: user: warning: [2025-02-14T08:09:55.602989745Z]: pre-flight checks failed: error parsing kubelet version: Invalid character(s) found in patch number "4@sha256:346676130195670ee7a1005946d1059a22983c32ec8c6a91a2e1bd8d4ac353bd"
1.2.3.4: user: warning: [2025-02-14T08:09:55.626673745Z]: [talos] task upgrade (1/1): failed: task "upgrade" failed: exit code 1
1.2.3.4: user: warning: [2025-02-14T08:09:55.627093745Z]: [talos] phase upgrade (10/14): failed
1.2.3.4: user: warning: [2025-02-14T08:09:55.627334745Z]: [talos] upgrade sequence: failed
1.2.3.4: user: warning: [2025-02-14T08:09:55.627505745Z]: [talos] upgrade failed: error running phase 10 in upgrade sequence: task 1/1: failed, task "upgrade" failed: exit code 1```

### Environment

- Talos version: v1.8.1 -> v1.9.3

### PR DESCRIPTION
**Pull request by robinelfrink**
# Pull Request

## What? (description)

Ignore the digest part of container images in machineconfig when checking semantic version validity through github.com/blang/semver/v4.

Closes #10373.

## Why? (reasoning)

We want to pin image digests, but pre-flight tries to validate tag _and_ digest for semantic versioning.

## Acceptance

Please use the following checklist:

- [x] you linked an issue (if applicable)
- [ ] you included tests (if applicable)
- [ ] you ran conformance (`make conformance`)
- [x] you formatted your code (`make fmt`)
- [ ] you linted your code (`make lint`)
- [ ] you generated documentation (`make docs`)
- [ ] you ran unit-tests (`make unit-tests`)

> See `make help` for a description of the available targets.

### CODE REVIEW

File: cmd/installer/pkg/install/preflight.go [hunk 1]
```diff
@@ -258,7 +258,7 @@ func kubernetesVersionFromImageRef(ref string) (*compatibility.KubernetesVersion
 		return nil, fmt.Errorf("invalid image reference: %q", ref)
 	}
 
-	return compatibility.ParseKubernetesVersion(ref[idx+2:])
+	return compatibility.ParseKubernetesVersion(strings.Split(ref[idx+2:], "@")[0])
```
Comment (smira) [inline cmd/installer/pkg/install/preflight.go:261]: this goes in the right direction, but we need a better fix from coding point of view

Comment (smira) [reply cmd/installer/pkg/install/preflight.go:261]: I will try to fix it up

**Review by smira — APPROVED** [review]

**Comment by smira** [comment]
thank you!
