### PR TITLE
fix: enable compression and bump gRPC max msg size

### LINKED ISSUE #7482: Unable to Apply extraManifest Due to gRPC Max Message Size Limit
## Bug Report
When attempting to apply extraManifest files larger than approximately 3.5MB, I encounter an issue due to the gRPC max message size being limited to 4MB.

### Logs
❯ t upgrade-k8s --dry-run --to 1.26.3
automatically detected the lowest Kubernetes version 1.26.3
discovered controlplane nodes ["10.232.55.195" "10.232.55.196" "10.232.55.197"]
discovered worker nodes ["10.232.55.198" "10.232.55.199"]
updating "kube-apiserver" to version "1.26.3"
 > "10.232.55.195": starting update
 > "10.232.55.196": starting update
 > "10.232.55.197": starting update
updating "kube-controller-manager" to version "1.26.3"
 > "10.232.55.195": starting update
 > "10.232.55.196": starting update
 > "10.232.55.197": starting update
updating "kube-scheduler" to version "1.26.3"
 > "10.232.55.195": starting update
 > "10.232.55.196": starting update
 > "10.232.55.197": starting update
updating kube-proxy to version "1.26.3"
 > "10.232.55.195": starting update
 > skipped in dry-run
 > "10.232.55.196": starting update
 > skipped in dry-run
 > "10.232.55.197": starting update
 > skipped in dry-run
updating kubelet to version "1.26.3"
 > "10.232.55.195": starting update
 > "10.232.55.196": starting update
 > "10.232.55.197": starting update
 > "10.232.55.198": starting update
 > "10.232.55.199": starting update
rpc error: code = ResourceExhausted desc = grpc: received message larger than max (5330853 vs. 4194304)

## Environment

- Talos version: \`talosctl version --nodes <problematic nodes>\`
- `talosctl version` output:
  ```plaintext
  Client:
    Tag:         v1.4.6
    SHA:         8615b213
    Built:
    Go version:  go1.20.5
    OS/Arch:     darwin/amd64
  Server:
    NODE:        10.232.55.195
    Tag:         v1.4.6
    SHA:         8615b213
    Built:
    Go version:  go1.20.5
    OS/Arch:     linux/amd64
    Enabled:     RBAC
- Kubernetes version: [`kubectl version --short`] - 1.26.3
- Platform: openstack

### PR DESCRIPTION
**Pull request by smira**
Fixes #7482

### CODE REVIEW

File: pkg/machinery/constants/constants.go [hunk 1]
```diff
@@ -881,6 +881,9 @@ const (
 
 	// MaintenanceServiceCommonName is the CN of the maintenance service server certificate.
 	MaintenanceServiceCommonName = "maintenance-service.talos.dev"
+
+	// GRPCMaxMessageSize is the maximum message size for Talos API.
+	GRPCMaxMessageSize = 32 * 1024 * 1024
```
Comment (frezbo) [inline pkg/machinery/constants/constants.go:886]: do we really want to support a 32 meg config patch :sweat_smile:

Comment (smira) [reply pkg/machinery/constants/constants.go:886]: not that big probably, but bump it up from a default 4 MiB limit. Watch API call returns old/new state, so 32 MiB will be split in a half, plus compression
