### PR TITLE
fix: sync PCR extension with volume provisioning lifecycle

### LINKED ISSUE #10665: sync PCR extension with volume provisioning
Ensure that volume encryption happens only before is PCR extended finally.

Document proper behavior, that TPM encryption might need a reboot.

### PR DESCRIPTION
**Pull request by smira**
Ensure volumes are not locked to the wrong value of PCR.

Fixes #10665

### CODE REVIEW

File: internal/app/machined/pkg/controllers/hardware/pcr_status.go [hunk 1]
```diff
@@ -0,0 +1,171 @@
...
+
+	runtimetalos "github.com/siderolabs/talos/internal/app/machined/pkg/runtime"
+	"github.com/siderolabs/talos/internal/pkg/secureboot"
+	"github.com/siderolabs/talos/internal/pkg/secureboot/tpm2"
+	"github.com/siderolabs/talos/pkg/machinery/constants"
+	"github.com/siderolabs/talos/pkg/machinery/resources/block"
+	"github.com/siderolabs/talos/pkg/machinery/resources/hardware"
+)
+
+// PCRStatusController populates PCI device information.
```
Comment (frezbo) [inline internal/app/machined/pkg/controllers/hardware/pcr_status.go:25]:
```suggestion
// PCRStatusController populates PCR status 
```

File: internal/app/machined/pkg/controllers/hardware/pcr_status.go
Comment (frezbo) [inline internal/app/machined/pkg/controllers/hardware/pcr_status.go:1]: this is nice, this allows us to extend with filesystem information and further allow user volumes to be locked to PCR

**Review by frezbo — APPROVED** [review]

File: internal/app/machined/pkg/controllers/hardware/pcr_status.go (hunk 1 above)
Comment (smira) [reply internal/app/machined/pkg/controllers/hardware/pcr_status.go]: thanks, fixed
