### PR TITLE
fix: use passed `--context` in `talosctl config` cmd

### LINKED ISSUE #6846: talosctl config endpoint/node ignores context
### Description

If a `talosconfig` file has more than one context and is used with commands `talosctl config endpoint` and `talosctl config node` the `--context` flag is ignored.

### Logs

```shell
❯ talosctl gen config foo https://foo.example.com:6443 --output "$(mktemp -d)"
generating PKI and tokens
Created /tmp/tmp.gi4UL2fvx4/controlplane.yaml
Created /tmp/tmp.gi4UL2fvx4/worker.yaml
Created /tmp/tmp.gi4UL2fvx4/talosconfig

❯ talosctl gen config bar https://bar.example.com:6443 --output "$(mktemp -d)"
generating PKI and tokens
Created /tmp/tmp.PRFTZEQase/controlplane.yaml
Created /tmp/tmp.PRFTZEQase/worker.yaml
Created /tmp/tmp.PRFTZEQase/talosconfig

# Merge the second talosconfig into the first
❯ talosctl --talosconfig /tmp/tmp.gi4UL2fvx4/talosconfig config merge /tmp/tmp.PRFTZEQase/talosconfig

# "Context" is 'bar'
❯ cat /tmp/tmp.gi4UL2fvx4/talosconfig
context: bar
contexts:
    bar:
        endpoints:
            - 127.0.0.1
        ca: ...
        crt: ...
        key: ...
    foo:
        endpoints:
            - 127.0.0.1
        ca: ...
        crt: ...
        key: ...

# Try to set nodes for 'foo'
❯ talosctl --talosconfig /tmp/tmp.gi4UL2fvx4/talosconfig --context foo config nodes 127.0.0.2

# See they were actually set for 'bar'
❯ cat /tmp/tmp.gi4UL2fvx4/talosconfig
context: bar
contexts:
    bar:
        endpoints:
            - 127.0.0.1
        nodes:
            - 127.0.0.2
        ca: ...
        crt: ...
        key: ...
    foo:
        endpoints:
            - 127.0.0.1
        ca: ...
        crt: ...
        key: ...
```

### Environment

- Talos version: `v.1.3.4`
- Kubernetes version: n/a
- Platform: Linux-amd64

### PR DESCRIPTION
**Pull request by DmitriyMV**
Use context from command line flags. Also some minor fixes.

Closes #6846

### CODE REVIEW

File: cmd/talosctl/cmd/talos/config.go [hunk 1]
```diff
@@ -127,8 +129,6 @@ var configContextCmd = &cobra.Command{
 			return err
 		}
 
-		c.Context = context
```
Comment (smira) [inline cmd/talosctl/cmd/talos/config.go:130]: isn't it what actually does the job in this command?

Comment (DmitriyMV) [reply cmd/talosctl/cmd/talos/config.go:130]: It is now moved [here](https://github.com/siderolabs/talos/pull/6868/files#diff-79095d8dc4c63f2ca9526001f07b86e5f486c035b2832847c6c3925618f6ad02R60).

Comment (smira) [reply cmd/talosctl/cmd/talos/config.go:130]: I don't think this is right, no command should change the current context except for this one.

Comment (DmitriyMV) [reply cmd/talosctl/cmd/talos/config.go:130]: `openConfigAndContext` receives empty context string in all cases except for `node`. Inside it verifies that `context` is empty and uses the one from the file. **Tim** wanted `talosctl config` to support `--context` flag, so we override Context field everywhere instead of only overriding it in `node`. That is actually quite consistent, no?

Comment (smira) [reply cmd/talosctl/cmd/talos/config.go:130]: Updating this field iirc changes the active context in talosconfig. Tim asked for the command to operate on the specified context, but not switch the context as a side effect. (I think that was it)

Comment (DmitriyMV) [reply cmd/talosctl/cmd/talos/config.go]: Oh, I understand now - the change will result in override context being set as **active** one and saved in `talosconfig` when we didn't want that. Reverted and pushed the different set of changes.

File: cmd/talosctl/cmd/talos/config.go [hunk 2]
```diff
@@ -446,9 +456,9 @@ Certificate expires: {{ .CertTTL }} ({{ .CertNotAfter }})
 //
 //nolint:goconst
 func configInfoCommand(config *clientconfig.Config, now time.Time) (string, error) {
-	context := config.Contexts[config.Context]
```
Comment (smira) [inline cmd/talosctl/cmd/talos/config.go:449]: should this be using `getContextData` as well?

**Review by smira — APPROVED** [review]
