### PR TITLE
fix(talosctl): protect k8sNames map writes with mutex

### LINKED ISSUE #13247: talosctl upgrade panics and skips reboot on multi-node upgrade (v1.13.0)
### Description
Running `talosctl upgrade` against multiple nodes can cause a client-side panic and may not complete the upgrade (nodes do not reboot into the new version).

Command used:
```bash id="n3k8pz"
talosctl upgrade \
  --nodes 10.0.0.1,10.0.0.2 \
  --image factory.talos.dev/metal-installer/88d1f7a5c4f1d3aba7df787c448c1d3d008ed29cfb34af53fa0df4336a56040b:v1.13.0
```

Observed behavior:
* Installer runs and writes new boot assets
* CLI reports `upgrade completed` for all nodes
* CLI crashes with `fatal error: concurrent map writes`
* Nodes remain running on the previous Talos version (no reboot into new version)

Repro characteristics:
* Reproduced 2 times when upgrading multiple nodes in a single command
* Did not reproduce on a subsequent third run
* Does not occur when upgrading nodes one-by-one
* Tested with:
  * 1× control plane node
  * 1× worker node
* Both nodes are running on the same physical hypervisor (Proxmox)
* Behavior appears timing/race-sensitive

Expected behavior:
* No client crash
* Nodes reboot and come up running the new Talos version
* Multi-node upgrade works as in previous versions

### Logs
```id="0h8lrf"
10.0.0.1: pulled image factory.talos.dev/metal-installer/88d1f7a5c4f1d3aba7df787c448c1d3d008ed29cfb34af53fa0df4336a56040b@sha256:31bd70ee4c271d698b138c693b8f66c2a4d2e38be0f1ee3d05a64f8e562580cf
10.0.0.2: pulled image factory.talos.dev/metal-installer/88d1f7a5c4f1d3aba7df787c448c1d3d008ed29cfb34af53fa0df4336a56040b@sha256:31bd70ee4c271d698b138c693b8f66c2a4d2e38be0f1ee3d05a64f8e562580cf
◳ 10.0.0.1: 2026/04/30 07:39:29 running Talos installer v1.13.0
◲ 10.0.0.1: 2026/04/30 07:39:29 running pre-flight checks
◱ 10.0.0.1: 2026/04/30 07:39:29 host Talos version: v1.13.0-rc.0
◰ 10.0.0.1: 2026/04/30 07:39:29 probing bootloader on "/dev/sda"
◳ 10.0.0.1: 2026/04/30 07:39:29 probing bootloader on "/dev/sda"
◲ 10.0.0.1: 2026/04/30 07:39:29 probing bootloader on "/dev/sda"
◱ 10.0.0.1: 2026/04/30 07:39:29 probing bootloader on "/dev/sda"
◰ 10.0.0.1: 2026/04/30 07:39:29 found GRUB bootloader on "/dev/sda"
◳ 10.0.0.1: 2026/04/30 07:39:29 found GRUB bootloader on "/dev/sda"
◲ 10.0.0.1: 2026/04/30 07:39:29 copying from io reader to /boot/B/vmlinuz
◱ 10.0.0.1: 2026/04/30 07:39:29 copying from io reader to /boot/B/initramfs.xz
◰ 10.0.0.1: 2026/04/30 07:39:29 writing /boot/grub/grub.cfg to disk
◳ 10.0.0.1: 2026/04/30 07:39:29 writing /boot/grub/grub.cfg to disk
◲ 10.0.0.1: 2026/04/30 07:39:29 executing: grub-install --boot-directory=/boot --removable --efi-directory=/boot/EFI /dev/sda
◱ 10.0.0.1: 2026/04/30 07:39:29 executing: grub-install --boot-directory=/boot --removable --efi-directory=/boot/EFI /dev/sda
◰ 10.0.0.1: 2026/04/30 07:39:29 executing: grub-install --boot-directory=/boot --removable --efi-directory=/boot/EFI /dev/sda
◳ 10.0.0.1: 2026/04/30 07:39:29 executing: grub-install --boot-directory=/boot --removable --efi-directory=/boot/EFI /dev/sda
◲ 10.0.0.1: 2026/04/30 07:39:42 META: loading from /dev/sda4
◱ 10.0.0.1: 2026/04/30 07:39:42 META: loaded 2 keys
◰ 10.0.0.1: 2026/04/30 07:39:42 META: saving to /dev/sda4
◳ 10.0.0.1: 2026/04/30 07:39:42 META: saved 3 keys
◲ 10.0.0.1: 2026/04/30 07:39:42 installation of v1.13.0 complete
10.0.0.1: upgrade completed
10.0.0.2: upgrade completed
fatal error: concurrent map writes

goroutine 185 [running]:
internal/runtime/maps.fatal({0x1054760e6?, 0x1082039c0?})
        runtime/panic.go:1181 +0x20
github.com/siderolabs/talos/cmd/talosctl/cmd/talos.drainNodes.func2()
        github.com/siderolabs/talos/cmd/talosctl/cmd/talos/drain.go:75 +0x128
golang.org/x/sync/errgroup.(*Group).Go.func1()
        golang.org/x/sync@v0.20.0/errgroup/errgroup.go:93 +0x4c
created by golang.org/x/sync/errgroup.(*Group).Go in goroutine 1
        golang.org/x/sync@v0.20.0/errgroup/errgroup.go:78 +0x90
```

### Environment
* Talos version: v1.13.0 (nodes were running v1.13.0-rc.0 before upgrade)
* Kubernetes version: Client Version: v1.36.0, Server Version: v1.36.0-rc.1
* Platform: Proxmox (VMs)

### PR DESCRIPTION
**Pull request by shanduur**
Concurrent goroutines wrote to k8sNames without synchronization,
causing a data race during drain. The comment claiming "no mutex
needed" was wrong - each goroutine writes a different key, but
the Go map implementation is not safe for concurrent writes.

Fixes #13247

Signed-off-by: Mateusz Urbanek <mateusz.urbanek@siderolabs.com>

### CODE REVIEW

File: cmd/talosctl/cmd/talos/drain.go [hunk 1]
```diff
@@ -41,8 +42,8 @@ func drainNodes(ctx context.Context, c *client.Client, nodes []string, drainTime
 	updateCh := make(chan nodeUpdate)
 
 	// k8sNames collects Talos IP -> K8s node name mappings produced by each goroutine.
-	// Each goroutine writes to its own slot, so no mutex is needed.
 	k8sNames := make(map[string]string, len(nodes))
+	mapMux := sync.Mutex{} // protects k8sNames map during writes
```
Comment (smira) [inline cmd/talosctl/cmd/talos/drain.go]: totally a nit, I would write that simply as

```
var mapMux sync.Mutex
```

File: cmd/talosctl/cmd/talos/drain.go [hunk 2]
```diff
@@ -72,7 +73,9 @@ func drainNodes(ctx context.Context, c *client.Client, nodes []string, drainTime
 				return fmt.Errorf("error resolving Kubernetes node name for %s: %w", node, resolveErr)
 			}
 
+			mapMux.Lock()
 			k8sNames[node] = k8sNodeName
```
Comment (smira) [inline cmd/talosctl/cmd/talos/drain.go:78]: do we need to lock when reading from it? or is it happening only after the stage we fill it?

**Review by smira — APPROVED** [review]

File: cmd/talosctl/cmd/talos/drain.go (hunk 2 above)
Comment (shanduur) [reply cmd/talosctl/cmd/talos/drain.go:78]: Reading occurs later in the loop rather than concurrently.
