### PR TITLE
fix: use controllers/resources for etcd configuration

### LINKED ISSUE #5889: etcd join and certificate fixes
fix a number of problems observed with etcd today:

1. join sequence - joining with the right hostname and certs
2. promotion to full member - figure out avoiding learner members
3. certificate generation - generate in the controller and update in the runtime as etcd supports reloading

### PR DESCRIPTION
**Pull request by smira**
This extracts etcd configuration and finalized run arguments as
resources managed by controllers.

The biggest change in terms of UX is that Talos now waits for the etcd
configured subnet to be actually available before starting etcd.
Previously etcd quickly failed if the requested subnet was not available
on the host.

Coupled with other fixes (#5951, #5988), this should bring etcd
join/promote sequence back into proper shape.

I also reverted all temporary measures for discovering etcd endpoints,
now etcd join doesn't depend on Kubernetes (once again).

Fixes #5889

Signed-off-by: Andrey Smirnov <andrey.smirnov@talos-systems.com>

### CODE REVIEW

File: internal/app/machined/pkg/controllers/etcd/config_test.go [hunk 1]
```diff
@@ -0,0 +1,70 @@
...
+		},
+	}
+
+	machineConfig := config.NewMachineConfig(cfg)
+	suite.Require().NoError(suite.State().Create(suite.Ctx(), machineConfig))
+
+	suite.AssertWithin(3*time.Second, 100*time.Millisecond, ctest.WrapRetry(func(assert *assert.Assertions, require *require.Assertions) {
+		etcdConfig, err := safe.StateGet[*etcd.Config](suite.Ctx(), suite.State(), etcd.NewConfig(etcd.NamespaceName, etcd.ConfigID).Metadata())
+		if err != nil {
+			assert.NoError(err)
```
Comment (frezbo) [inline internal/app/machined/pkg/controllers/etcd/config_test.go:61]: :thinking: I didn't quite get this check here

File: internal/app/machined/pkg/controllers/etcd/spec.go [hunk 2]
```diff
@@ -0,0 +1,149 @@
...
+		ips, err := net.IPAddrs()
+		if err != nil {
+			return fmt.Errorf("error listing IPs: %w", err)
+		}
+
+		listenAddress := netip.IPv4Unspecified()
+
+		for _, ip := range ips {
+			if ip.To4() == nil {
+				listenAddress = netip.IPv6Unspecified()
```
Comment (frezbo) [inline internal/app/machined/pkg/controllers/etcd/spec.go:117]: shouldn't we be able to listen on both ipv4 and ipv6?

File: internal/app/machined/pkg/system/services/etcd.go [hunk 3]
```diff
@@ -386,19 +391,14 @@ func (e *Etcd) argsForInit(ctx context.Context, r runtime.Runtime) error {
 		_, upgraded = meta.LegacyADV.ReadTag(adv.Upgrade)
 	}
 
-	primaryAddr, listenAddress, err := primaryAndListenAddresses(r.Config().Cluster().Etcd().Subnet())
-	if err != nil {
-		return fmt.Errorf("failed to calculate etcd addresses: %w", err)
-	}
-
 	// TODO(scm): see issue #2121 and description below in argsForControlPlane.
```
Comment (frezbo) [inline internal/app/machined/pkg/system/services/etcd.go:394]: seems this issue is already closed

**Review by frezbo — APPROVED** [review]

File: internal/app/machined/pkg/controllers/etcd/spec.go (hunk 2 above)
Comment (smira) [reply internal/app/machined/pkg/controllers/etcd/spec.go:117]: I believe listening on IPv6 implies listening on IPv4.

This issue is that if IPv6 is disabled, we can't listen on IPv6 `::`

File: internal/app/machined/pkg/controllers/etcd/config_test.go (hunk 1 above)
Comment (smira) [reply internal/app/machined/pkg/controllers/etcd/config_test.go:61]: the idea is that `assert.` continues retrying, but `require.` stops retrying

so if we failed to get a resources, it's a retryable failure, but we also want not to proceed further as `etcdConfig` is `nil`

File: internal/app/machined/pkg/system/services/etcd.go (hunk 3 above)
Comment (smira) [reply internal/app/machined/pkg/system/services/etcd.go:394]: ok, this one was actually closed by mistake... there's a new one #5668 which I pulled into the v1.2, as it's relatively easy to implement now. anyways, this comment is outdated

File: internal/app/machined/pkg/controllers/etcd/spec.go [hunk 4]
```diff
@@ -0,0 +1,149 @@
...
+
+				break
+			}
+		}
+
+		// we use stdnet.IP here to re-use already existing functions in talos-systems/net
+		// once talos-systems/net is migrated to netaddr or netip, we can use it here
```
Comment (Unix4ever) [inline internal/app/machined/pkg/controllers/etcd/spec.go:124]: Would be great to have a ticket for migration and link it as `TODO` here :)
but not a great deal.

**Review by Unix4ever — APPROVED** [review]

File: internal/app/machined/pkg/controllers/etcd/spec.go (hunk 4 above)
Comment (smira) [reply internal/app/machined/pkg/controllers/etcd/spec.go:124]: yep, I'm thinking about it... it will simplify testing a lot as well

File: pkg/machinery/resources/etcd/spec.go [hunk 5]
```diff
@@ -0,0 +1,63 @@
...
+		Aliases:          []resource.Type{},
+		DefaultNamespace: NamespaceName,
+		PrintColumns: []meta.PrintColumn{
+			{
+				Name:     "Name",
+				JSONPath: "{.name}",
+			},
+			{
+				Name:     "AdvertisedAddress",
+				JSONPath: "{.advertistedAddress}",
```
Comment (sauterp) [inline pkg/machinery/resources/etcd/spec.go:59]:
```suggestion
				JSONPath: "{.advertisedAddress}",
```

File: pkg/machinery/resources/etcd/spec.go [hunk 6]
```diff
@@ -0,0 +1,63 @@
...
+
+// Spec resource holds status of rendered secrets.
+type Spec = typed.Resource[SpecSpec, SpecRD]
+
+// SpecSpec describes (some) Specuration settings of etcd.
+//
+//gotagsrewrite:gen
+type SpecSpec struct {
+	Name              string            `yaml:"name" protobuf:"1"`
+	AdvertisedAddress netip.Addr        `yaml:"advertistedAddress" protobuf:"2"`
```
Comment (sauterp) [inline pkg/machinery/resources/etcd/spec.go:29]:
```suggestion
	AdvertisedAddress netip.Addr        `yaml:"advertisedAddress" protobuf:"2"`
```

**Review by sauterp — CHANGES_REQUESTED** [review]

**Review by sauterp — APPROVED** [review]
