### PR TITLE
fix: registry mirror fallback handling

### LINKED ISSUE #9613: adjust Talos resolver to use upstream as a fallback
There's a mismatch between Talos docker resolver and containerd one: containerd defaults to having original endpoint (e.g. ghcr.io) as a fallback, while Talos doesn't.

Talos resolver is used to pull installer, etcd, kubelet images, while containerd pulls all other images.

> Note: this statement might need additional verification.

### PR DESCRIPTION
**Pull request by smira**
Fixes #9613

This has two changes:

* adjust Talos registry resolver to match containerd (CRI) resolver: use by default upstream as a fallback
* add a machine config option to skip upstream as a fallback, and adjust CRI configuration accordingly

See https://github.com/containerd/containerd/blob/main/docs/hosts.md#registry-configuration---examples for details on CRI's `hosts.toml`.

### CODE REVIEW

File: internal/pkg/containers/image/resolver.go [hunk 1]
```diff
@@ -97,25 +98,54 @@ func RegistryHosts(reg config.Registries) docker.RegistryHosts {
...
+	OverridePath bool
+}
+
+// RegistryEndpointEntriesFromConfig returns registry endpoints per host.
+func RegistryEndpointEntriesFromConfig(host string, reg config.RegistryMirrorConfig) ([]EndpointEntry, error) {
+	entries := xslices.Map(reg.Endpoints(), func(endpoint string) EndpointEntry {
+		return EndpointEntry{Endpoint: endpoint, OverridePath: reg.OverridePath()}
+	})
+
+	if !reg.SkipFallback() {
```
Comment (dsseng) [inline internal/pkg/containers/image/resolver.go:113]: nit: just return when skipping to reduce code nesting?

**Review by dsseng — APPROVED** [review]

File: internal/pkg/containers/image/resolver.go (hunk 1 above)
Comment (smira) [reply internal/pkg/containers/image/resolver.go:113]: yeah good idea, thanks, I will update!
