### PR TITLE
fix: mount throws EPERM on virtiofs with SELinux

### LINKED ISSUE #13245: Talos 1.13 virtiofs ExternalVolumeConfig fails with SELinux enabled in permissive mode
### Description

In Talos 1.13, virtiofs-backed ExternalVolumeConfig mounts fail when SELinux is enabled but running in permissive mode.

The failure happens when the MountController tries to set the SELinux label on the external volume mount path under /var/mnt. The virtiofs mount appears to fail because setting the security.selinux xattr returns EPERM:
```
xattr.LSet /var/mnt/DVR security.selinux: operation not permitted
```
The same virtiofs external volume works when booting Talos with selinux=0.

This looks unexpected because the node is not running SELinux in enforcing mode. The node reports:
```
SELINUXSTATE: enabled, permissive
```
Kernel command line includes `selinux=1` but does not include `enforcing=1`.

The Talos 1.13 virtiofs documentation mentions that virtiofs external volumes are not supported when SELinux is running in enforcing mode, but in this case SELinux is permissive. I would expect either:

1. virtiofs external volumes to work when SELinux is enabled but permissive, or
2. Talos to document that virtiofs external volumes currently require SELinux to be disabled entirely, not merely non-enforcing, or
3. the SELinux labeling failure on virtiofs to be handled as non-fatal when the underlying filesystem returns EPERM for security.selinux xattr operations.

Example ExternalVolumeConfig:

```yaml
apiVersion: v1alpha1
kind: ExternalVolumeConfig
name: DVR
filesystemType: virtiofs
mount:
    secure: true
    virtiofs:
        tag: DVR
```

Workaround tested:

Booting the same node with selinux=0 makes the virtiofs external volume work:

```text
talosctl -n 192.168.147.4 get volumestatus x-DVR
NODE            NAMESPACE   TYPE           ID      VERSION   TYPE       PHASE   LOCATION   SIZE
192.168.147.4   runtime     VolumeStatus   x-DVR   2         external   ready   DVR     
```

### Logs

MountController failure with SELinux enabled/permissive:

```text
192.168.147.4: 2026-04-29T16:32:34.061Z INFO mounting "DVR" to "/var/mnt/DVR" {"component": "controller-runtime", "controller": "block.MountController", "mount_request.id": "x-DVR"}
192.168.147.4: 2026-04-29T16:32:34.061Z DEBUG image cache status {"component": "controller-runtime", "controller": "cri.ImageCacheConfigController", "status": "disabled", "copy_status": "skipped"}
192.168.147.4: 2026-04-29T16:32:34.066Z ERROR controller failed {"component": "controller-runtime", "controller": "block.MountController", "error": "failed to mount \"x-DVR\": failed to mount: 1 error(s) occurred:\n\terror setting selinux label on \"/var/mnt/DVR\": xattr.LSet /var/mnt/DVR security.selinux: operation not permitted"}
```

Security state:

```text
NODE            NAMESPACE   TYPE            ID              VERSION   SECUREBOOT   UKISIGNINGKEYFINGERPRINT   PCRSIGNINGKEYFINGERPRINT   SELINUXSTATE          MODULESIGNATUREENFORCED
192.168.147.4   runtime     SecurityState   securitystate   1         false                                                              enabled, permissive   true
```

Kernel command line / SELinux-related dmesg output:

```text
192.168.147.4: kern:    info: [2026-04-29T16:39:09.936797449Z]: Command line: talos.platform=metal talos.config=none console=tty0 console=ttyS0 init_on_alloc=1 slab_nomerge pti=on consoleblank=0 nvme_core.io_timeout=4294967295 printk.devkmsg=on selinux=1 module.sig_enforce=1 module.sig_enforce=1 proc_mem.force_override=never net.ifnames=0
192.168.147.4: kern:  notice: [2026-04-29T16:39:09.998237066Z]: Kernel command line: talos.platform=metal talos.config=none console=tty0 console=ttyS0 init_on_alloc=1 slab_nomerge pti=on consoleblank=0 nvme_core.io_timeout=4294967295 printk.devkmsg=on selinux=1 module.sig_enforce=1 module.sig_enforce=1 proc_mem.force_override=never net.ifnames=0
192.168.147.4: kern:  notice: [2026-04-29T16:39:09.998414572Z]: Unknown kernel command line parameters "selinux=1", will be passed to user space.
192.168.147.4: kern:    info: [2026-04-29T16:39:10.283239372Z]: LSM: initializing lsm=lockdown,capability,yama,selinux,bpf,landlock
192.168.147.4: kern:   debug: [2026-04-29T16:39:11.799480351Z]:     selinux=1
192.168.147.4: user: warning: [2026-04-29T16:39:11.974112137Z]: [talos] [initramfs] selinux: loading policy
192.168.147.4: kern:  notice: [2026-04-29T16:39:12.031768778Z]: audit: type=1403 audit(1777480751.483:2): auid=4294967295 ses=4294967295 lsm=selinux res=1
192.168.147.4: user: warning: [2026-04-29T16:39:12.03178499Z]: [talos] [initramfs] selinux: policy loaded
192.168.147.4: user: warning: [2026-04-29T16:39:33.382971195Z]: [talos] controller failed {"component": "controller-runtime", "controller": "block.MountController", "error": "failed to mount \"x-DVR\": failed to mount: 1 error(s) occurred:\n\terror setting selinux label on \"/var/mnt/DVR\": xattr.LSet /var/mnt/DVR security.selinux: operation not permitted"}
```

Repeated MountController failures:

```text
192.168.147.4: user: warning: [2026-04-29T16:39:35.580889791Z]: [talos] controller failed {"component": "controller-runtime", "controller": "block.MountController", "error": "failed to mount \"x-DVR\": failed to mount: 1 error(s) occurred:\n\terror setting selinux label on \"/var/mnt/DVR\": xattr.LSet /var/mnt/DVR security.selinux: operation not permitted"}
192.168.147.4: user: warning: [2026-04-29T16:39:38.036414285Z]: [talos] controller failed {"component": "controller-runtime", "controller": "block.MountController", "error": "failed to mount \"x-DVR\": failed to mount: 1 error(s) occurred:\n\terror setting selinux label on \"/var/mnt/DVR\": xattr.LSet /var/mnt/DVR security.selinux: operation not permitted"}
192.168.147.4: user: warning: [2026-04-29T16:39:45.557031224Z]: [talos] controller failed {"component": "controller-runtime", "controller": "block.MountController", "error": "failed to mount \"x-DVR\": failed to mount: 1 error(s) occurred:\n\terror setting selinux label on \"/var/mnt/DVR\": xattr.LSet /var/mnt/DVR security.selinux: operation not permitted"}
192.168.147.4: user: warning: [2026-04-29T16:39:57.801868358Z]: [talos] controller failed {"component": "controller-runtime", "controller": "block.MountController", "error": "failed to mount \"x-DVR\": failed to mount: 1 error(s) occurred:\n\terror setting selinux label on \"/var/mnt/DVR\": xattr.LSet /var/mnt/DVR security.selinux: operation not permitted"}
```

Result after booting with selinux=0:

```text
talosctl -n 192.168.147.4 get volumestatus x-DVR
NODE            NAMESPACE   TYPE           ID      VERSION   TYPE       PHASE   LOCATION   SIZE
192.168.147.4   runtime     VolumeStatus   x-DVR   2         external   ready   DVR     
```

### Environment

- Talos version: 1.13.0
- Kubernetes version: 1.35.4
- Platform: metal / QEMU virtiofs-backed VM on unraid 7.2.3

### PR DESCRIPTION
**Pull request by shanduur**
This ignores relabeling error (returning `EPERM`) of virtiofs mounts with SELinux enabled in either enforcing or permissive mode.

Fixes #13245

Signed-off-by: Mateusz Urbanek <mateusz.urbanek@siderolabs.com>

### CODE REVIEW

File: internal/pkg/mount/v3/point.go [hunk 1]
```diff
@@ -103,8 +105,14 @@ func FilterSelinuxLabelErrors(target, fstype string, err error) error {
 		return nil
 	}
 
-	if fstype == "virtiofs" && errors.Is(err, unix.EROFS) {
-		return nil
+	if fstype == "virtiofs" {
+		switch {
+		case errors.Is(err, unix.EROFS):
+			return nil
+		case errors.Is(err, unix.EPERM):
```
Comment (frezbo) [inline internal/pkg/mount/v3/point.go:112]: unix.EPERM might be returned for several others reasons too i believe

Comment (shanduur) [reply internal/pkg/mount/v3/point.go:112]: This function is only used on relabeling errors, and EPERM is only checked for `virtiofs`. Virtiofsd will return EPERM on `security.` labels most of the time, and needs to be compiled with libcap and run with `CAP_SYS_ADMIN` and passed correct `xattrmap` to allow `security.` labels to be preserved.

**Review by smira — APPROVED** [review]

File: pkg/provision/providers/vm/virtiofsd.go [hunk 2]
```diff
@@ -43,6 +51,8 @@ func Virtiofsd(ctx context.Context, virtiofsdBin, share, socket string) error {
 		"--socket-path", socket,
 		"--announce-submounts",
 		"--inode-file-handles=mandatory",
+		"--xattr",
+		"--xattrmap=" + xattrmap,
 	}
```
[the remark this answers is not in the document]
Comment (shanduur) [reply pkg/provision/providers/vm/virtiofsd.go:56]: We are using correct version of virtiofsd in CI and if someone wants to run the dev clusters needs the correct one as well.

**Review by frezbo — APPROVED** [review]
