### PR TITLE
fix: add more resilient move

### LINKED ISSUE #12259: images cache-create fails to copy tmp folder
## Bug Report

When using talosctl 1.12.0-beta.0 this command
```
cat images.txt | ./talosctl images cache-create --layout flat --image-cache-path ./image-cache.flat --images=-
```
fails with the following error
```
error generating cache: rename /tmp/talos-image-cache-gen370585548 ./image-cache.flat: invalid cross-device link
```
If I change the cache path to `/tmp/image-cache.flat` the command works. I also tried specifying the full path to $PWD and I get the same error.

### Environment

- Platform: linux

### PR DESCRIPTION
**Pull request by shanduur**
Fixes #12259

Signed-off-by: Mateusz Urbanek <mateusz.urbanek@siderolabs.com>

### CODE REVIEW

File: pkg/imager/cache/cache.go [hunk 1]
```diff
@@ -185,6 +187,78 @@ func Generate(images []string, platforms []string, insecure bool, imageLayerCach
 	return removeAll()
 }
 
+func move(src, dest string) error {
+	if err := os.Rename(src, dest); err == nil {
+		return nil
+	} else if !errors.Is(err, syscall.EXDEV) {
```
Comment (frezbo) [inline pkg/imager/cache/cache.go:193]: TIL 😅

**Review by frezbo — APPROVED** [review]

File: pkg/imager/cache/cache.go (hunk 1 above)
Comment (shanduur) [reply pkg/imager/cache/cache.go:193]: Yeah, same 🥲
