### PR TITLE
fix: bump priority of OpenStack routes if IPv6 and default gateway

### LINKED ISSUE #8619: IPv6 on OpenStack using SLAAC does not set route correctly
## Bug Report

Continuation of https://github.com/siderolabs/talos/issues/8558.

### Description

It all started with:
```
control-plane-1: user: warning: [2024-04-19T12:33:36.812989927Z]: [talos] controller failed {"component": "controller-runtime", "controller": "network.RouteSpecController", "error": "1 error occurred:\n\t* error adding route: netlink receive: file exists, message {Family:10 DstLength:0 SrcLength:0 Tos:0 Table:0 Protocol:4 Scope:0 Type:1 Flags:0 Attributes:{Dst:<nil> Src:<nil> Gateway:<ipv6_address>::1 OutIface:8 Priority:1024 Table:254 Mark:0 Pref:<nil> Expires:<nil> Metrics:<nil> Multipath:[]}}\n\n"}
```

I did however look at the source code of Talos, and noticed the following:

https://github.com/siderolabs/talos/blob/d7c3a0735eab85dd24e86fe3e0872253067e8f10/internal/app/machined/pkg/runtime/v1alpha1/platform/openstack/openstack.go#L242-L243

From my network dump. ` "type": "ipv6_slaac"`.  I'm not sure if it's related, but I noticed that `ipv6_slaac` was not even part of the test data.

### Logs

- OpenStack network metadata dump
- Talos boot logs
- Dump of the route specs

[route_logs.tgz](https://github.com/siderolabs/talos/files/15040532/route_logs.tgz)  - _Must decrypt._

### Environment

```
$ talosctl --talosconfig talosconfig version -n 10.10.10.51
Client:
	Tag:         v1.6.7
	SHA:         46c8ac10
	Built:       
	Go version:  go1.21.8 X:loopvar
	OS/Arch:     darwin/arm64
Server:
	NODE:        10.10.10.51
	Tag:         v1.7.0-beta.1
	SHA:         77581447
	Built:       
	Go version:  go1.22.2
	OS/Arch:     linux/amd64
	Enabled:     RBAC
```

- Platform: OpenStack

### PR DESCRIPTION
**Pull request by smira**
IT looks like gateway is sometimes reported as a 'route' skipping a 'gateway' field.

Fixes #8619

### CODE REVIEW

File: internal/app/machined/pkg/runtime/v1alpha1/platform/openstack/openstack.go [hunk 1]
```diff
@@ -328,6 +328,11 @@ func (o *Openstack) ParseMetadata(
 
 			route.Normalize()
 
+			// double the priority of the route is that actually the default gateway and IPv6
```
Comment (frezbo) [inline internal/app/machined/pkg/runtime/v1alpha1/platform/openstack/openstack.go:331]:
```suggestion
			// double the priority of the route if that is actually the default gateway and IPv6
```

**Review by frezbo — APPROVED** [review]
