### PR TITLE
fix: allow META encoded values to be compressed

### LINKED ISSUE #8186: Support bigger META values via `INSTALLER_META` environment variable
Talos support for compression of `INSTALLER_META` values to handle big META values which overflow kernel cmdline.

### PR DESCRIPTION
**Pull request by smira**
Fixes #8186

This is planned to be backported to Talos 1.6.3.

This allows to pass large META values (YAML for platform network configuration) which might otherwise exceed the limit for kernel command line params.

### CODE REVIEW

**Comment by smira** [comment]
(needs some more docs updates and testing)

File: pkg/machinery/meta/meta.go [hunk 1]
```diff
@@ -82,3 +123,11 @@ func DecodeValues(s string) (Values, error) {
 
 	return result, nil
 }
+
+func hasGzipMagic(b []byte) bool {
+	if len(b) < 2 {
+		return false
+	}
+
+	return b[0] == 0x1f && b[1] == 0x8b
```
Comment (frezbo) [inline pkg/machinery/meta/meta.go:132]: maybe a comment here from the spec?

Comment (smira) [reply pkg/machinery/meta/meta.go:132]: what kind of comment are you looking for?

Comment (smira) [reply pkg/machinery/meta/meta.go:132]: it's gzip magic number as the function name suggests!

https://cs.opensource.google/go/go/+/refs/tags/go1.21.6:src/compress/gzip/gunzip.go;l=20-21

Comment (smira) [reply pkg/machinery/meta/meta.go:132]: but I see your point

File: pkg/machinery/meta/meta.go [hunk 2]
```diff
@@ -66,6 +90,23 @@ func DecodeValues(s string) (Values, error) {
...
+		}
+
+		b, err = io.ReadAll(gzR)
+		if err != nil {
+			return nil, err
+		}
+
+		if err := gzR.Close(); err != nil {
+			return nil, err
+		}
```
Comment (utkuozdemir) [inline pkg/machinery/meta/meta.go:107]: shouldn't we do this using `defer` - to make sure it closes unconditionally even if `ReadAll` fails?

**Review by utkuozdemir — APPROVED** [review]

File: pkg/machinery/meta/meta.go (hunk 2 above)
Comment (smira) [reply pkg/machinery/meta/meta.go:107]: I think it'd be more clear, but I think it's not relevant, `.Close()` verifies the checksum, it actually doesn't close (like deallocate) anything

Comment (smira) [reply pkg/machinery/meta/meta.go:109]: updated with deferred Close
