### PR TITLE
fix: automatically discard VIPs for etcd advertised addresses

### LINKED ISSUE #6210: etcd shouldn't advertise VIPs by default

### PR DESCRIPTION
**Pull request by smira**
Fixes #6210

Refactored the code a bit to support excludes and default configuration.

Etcd should never advertise VIPs, as VIPs are managed by etcd elections.

Signed-off-by: Andrey Smirnov <andrey.smirnov@talos-systems.com>

### CODE REVIEW

File: internal/app/machined/pkg/controllers/etcd/config.go [hunk 1]
```diff
@@ -92,12 +92,27 @@ func (ctrl *ConfigController) Run(ctx context.Context, r controller.Runtime, log
 			return fmt.Errorf("error getting machine config: %w", err)
 		}
 
-		if err = safe.WriterModify(ctx, r, etcd.NewConfig(etcd.NamespaceName, etcd.ConfigID), func(status *etcd.Config) error {
-			status.TypedSpec().AdvertiseValidSubnets = machineConfig.Config().Cluster().Etcd().AdvertisedSubnets()
-			status.TypedSpec().ListenValidSubnets = machineConfig.Config().Cluster().Etcd().ListenSubnets()
+		if err = safe.WriterModify(ctx, r, etcd.NewConfig(etcd.NamespaceName, etcd.ConfigID), func(cfg *etcd.Config) error {
+			cfg.TypedSpec().AdvertiseValidSubnets = machineConfig.Config().Cluster().Etcd().AdvertisedSubnets()
+			cfg.TypedSpec().AdvertiseExcludeSubnets = nil
```
Comment (frezbo) [inline internal/app/machined/pkg/controllers/etcd/config.go:97]: excludesubnets already defined earlier?

**Review by frezbo — APPROVED** [review]

File: internal/app/machined/pkg/controllers/etcd/config.go (hunk 1 above)
Comment (smira) [reply internal/app/machined/pkg/controllers/etcd/config.go:97]: this makes sure we start with an empty list, otherwise `append()` below will keep appending more and more copies of the same VIP

Comment (frezbo) [reply internal/app/machined/pkg/controllers/etcd/config.go:97]: https://github.com/siderolabs/talos/blob/dce923f7471a73623c7bc99e376e51a53401faae/pkg/machinery/resources/etcd/config.go#L30 i was not sure if it was defined, checked and confirmed.
