### PR TITLE
test: fix some flaky tests

### LINKED ISSUE #10837: TestProcessSuite/runReaper=false/TestRunLogs
```
#177 39.28 === RUN   TestProcessSuite/runReaper=false/TestRunLogs
#177 39.28 2025/04/30 13:03:43 state Running: Process Process(["/bin/bash" "-c" "echo -n \"Test 1\nTest 2\n\""]) started with PID 12750
#177 39.28     process_test.go:96: 
#177 39.28         	Error Trace:	/src/internal/app/machined/pkg/system/runner/process/process_test.go:96
#177 39.28         	Error:      	Not equal: 
#177 39.28         	            	expected: []byte{0x54, 0x65, 0x73, 0x74, 0x20, 0x31, 0xa, 0x54, 0x65, 0x73, 0x74, 0x20, 0x32, 0xa}
#177 39.28         	            	actual  : []byte{}
#177 39.28         	            	
#177 39.28         	            	Diff:
#177 39.28         	            	--- Expected
#177 39.28         	            	+++ Actual
#177 39.28         	            	@@ -1,3 +1,2 @@
#177 39.28         	            	-([]uint8) (len=14) {
#177 39.28         	            	- 00000000  54 65 73 74 20 31 0a 54  65 73 74 20 32 0a        |Test 1.Test 2.|
#177 39.28         	            	+([]uint8) {
#177 39.28         	            	 }
#177 39.28         	Test:       	TestProcessSuite/runReaper=false/TestRunLogs
#177 39.28 --- FAIL: TestProcessSuite (2.44s)
#177 39.28     --- PASS: TestProcessSuite/runReaper=true (1.38s)
#177 39.28         --- PASS: TestProcessSuite/runReaper=true/TestIOPriority (0.03s)
#177 39.28         --- PASS: TestProcessSuite/runReaper=true/TestPriority (1.02s)
#177 39.28         --- PASS: TestProcessSuite/runReaper=true/TestRunLogs (0.00s)
#177 39.28         --- PASS: TestProcessSuite/runReaper=true/TestRunRestartFailed (0.10s)
#177 39.28         --- PASS: TestProcessSuite/runReaper=true/TestRunSuccess (0.00s)
#177 39.28         --- PASS: TestProcessSuite/runReaper=true/TestSchedulingPolicy (0.03s)
#177 39.28         --- PASS: TestProcessSuite/runReaper=true/TestStopFailingAndRestarting (0.08s)
#177 39.28         --- PASS: TestProcessSuite/runReaper=true/TestStopSigKill (0.11s)
#177 39.28     --- FAIL: TestProcessSuite/runReaper=false (1.06s)
#177 39.28         --- PASS: TestProcessSuite/runReaper=false/TestIOPriority (0.03s)
#177 39.28         --- PASS: TestProcessSuite/runReaper=false/TestPriority (1.02s)
#177 39.28         --- FAIL: TestProcessSuite/runReaper=false/TestRunLogs (0.01s)
```

### LINKED ISSUE #10934: TestCmdline
```
#174 61.65 === NAME  TestCmdlineParse/no_iface
#174 61.65     cmdline_test.go:624: 
#174 61.65         	Error Trace:	/src/internal/app/machined/pkg/controllers/network/cmdline_test.go:624
#174 61.65         	Error:      	Not equal: 
#174 61.65         	            	expected: network.CmdlineNetworking{LinkConfigs:[]network.CmdlineLinkConfig{network.CmdlineLinkConfig{LinkName:"eth0", Address:netip.Prefix{ip:netip.Addr{addr:netip.uint128{hi:0x0, lo:0xffffac140002}, z:unique.Handle[net/netip.addrDetail]{value:(*netip.addrDetail)(0xc00000fcf8)}}, bitsPlusOne:0x21}, Gateway:netip.Addr{addr:netip.uint128{hi:0x0, lo:0xffffac140001}, z:unique.Handle[net/netip.addrDetail]{value:(*netip.addrDetail)(0xc00000fcf8)}}, DHCP:false}}, Hostname:"", DNSAddresses:[]netip.Addr(nil), NTPAddresses:[]netip.Addr(nil), IgnoreInterfaces:[]string(nil), NetworkLinkSpecs:[]network.LinkSpecSpec{network.LinkSpecSpec{Name:"eth0", Logical:false, Up:true, MTU:0x0, Kind:"", Type:0x0, ParentName:"", BondSlave:network.BondSlave{MasterName:"", SlaveIndex:0}, BridgeSlave:network.BridgeSlave{MasterName:""}, VLAN:network.VLANSpec{VID:0x0, Protocol:0x0}, BondMaster:network.BondMasterSpec{Mode:0x0, HashPolicy:0x0, LACPRate:0x0, ARPValidate:0x0, ARPAllTargets:0x0, PrimaryIndex:0x0, PrimaryReselect:0x0, FailOverMac:0x0, ADSelect:0x0, MIIMon:0x0, UpDelay:0x0, DownDelay:0x0, ARPInterval:0x0, ResendIGMP:0x0, MinLinks:0x0, LPInterval:0x0, PacketsPerSlave:0x0, NumPeerNotif:0x0, TLBDynamicLB:0x0, AllSlavesActive:0x0, UseCarrier:false, ADActorSysPrio:0x0, ADUserPortKey:0x0, PeerNotifyDelay:0x0}, BridgeMaster:network.BridgeMasterSpec{STP:network.STPSpec{Enabled:false}, VLAN:network.BridgeVLANSpec{FilteringEnabled:false}}, Wireguard:network.WireguardSpec{PrivateKey:"", PublicKey:"", ListenPort:0, FirewallMark:0, Peers:[]network.WireguardPeer(nil)}, ConfigLayer:1}}}
#174 61.65         	            	actual  : network.CmdlineNetworking{LinkConfigs:[]network.CmdlineLinkConfig{network.CmdlineLinkConfig{LinkName:"dummy2e19ff", Address:netip.Prefix{ip:netip.Addr{addr:netip.uint128{hi:0x0, lo:0xffffac140002}, z:unique.Handle[net/netip.addrDetail]{value:(*netip.addrDetail)(0xc00000fcf8)}}, bitsPlusOne:0x21}, Gateway:netip.Addr{addr:netip.uint128{hi:0x0, lo:0xffffac140001}, z:unique.Handle[net/netip.addrDetail]{value:(*netip.addrDetail)(0xc00000fcf8)}}, DHCP:false}}, Hostname:"", DNSAddresses:[]netip.Addr(nil), NTPAddresses:[]netip.Addr(nil), IgnoreInterfaces:[]string(nil), NetworkLinkSpecs:[]network.LinkSpecSpec{network.LinkSpecSpec{Name:"dummy2e19ff", Logical:false, Up:true, MTU:0x0, Kind:"", Type:0x0, ParentName:"", BondSlave:network.BondSlave{MasterName:"", SlaveIndex:0}, BridgeSlave:network.BridgeSlave{MasterName:""}, VLAN:network.VLANSpec{VID:0x0, Protocol:0x0}, BondMaster:network.BondMasterSpec{Mode:0x0, HashPolicy:0x0, LACPRate:0x0, ARPValidate:0x0, ARPAllTargets:0x0, PrimaryIndex:0x0, PrimaryReselect:0x0, FailOverMac:0x0, ADSelect:0x0, MIIMon:0x0, UpDelay:0x0, DownDelay:0x0, ARPInterval:0x0, ResendIGMP:0x0, MinLinks:0x0, LPInterval:0x0, PacketsPerSlave:0x0, NumPeerNotif:0x0, TLBDynamicLB:0x0, AllSlavesActive:0x0, UseCarrier:false, ADActorSysPrio:0x0, ADUserPortKey:0x0, PeerNotifyDelay:0x0}, BridgeMaster:network.BridgeMasterSpec{STP:network.STPSpec{Enabled:false}, VLAN:network.BridgeVLANSpec{FilteringEnabled:false}}, Wireguard:network.WireguardSpec{PrivateKey:"", PublicKey:"", ListenPort:0, FirewallMark:0, Peers:[]network.WireguardPeer(nil)}, ConfigLayer:1}}}
#174 61.65         	            	
#174 61.65         	            	Diff:
#174 61.65         	            	--- Expected
#174 61.65         	            	+++ Actual
#174 61.65         	            	@@ -3,3 +3,3 @@
#174 61.65         	            	   (network.CmdlineLinkConfig) {
#174 61.65         	            	-   LinkName: (string) (len=4) "eth0",
#174 61.65         	            	+   LinkName: (string) (len=11) "dummy2e19ff",
#174 61.65         	            	    Address: (netip.Prefix) {
#174 61.65         	            	@@ -40,3 +40,3 @@
#174 61.65         	            	   (network.LinkSpecSpec) {
#174 61.65         	            	-   Name: (string) (len=4) "eth0",
#174 61.65         	            	+   Name: (string) (len=11) "dummy2e19ff",
#174 61.65         	            	    Logical: (bool) false,
#174 61.65         	Test:       	TestCmdlineParse/no_iface
```

### PR DESCRIPTION
**Pull request by smira**
Fixes #10837

Fixes #10934

### CODE REVIEW

File: internal/app/machined/pkg/system/runner/process/process.go [hunk 1]
```diff
@@ -214,13 +214,17 @@ func (p *processRunner) build() (commandWrapper, error) {
 		return commandWrapper{}, err
 	}
 
-	go io.Copy(writer, pr) //nolint:errcheck
+	go func() {
+		defer pr.Close() //nolint:errcheck
```
Comment (smira) [inline internal/app/machined/pkg/system/runner/process/process.go:218]: this was a bug, copying from `pr` to `writer` was not synchronized with closing `pr` - there is a chance that `pr` will be closed before copying is done

File: internal/pkg/dns/dns_test.go [hunk 2]
```diff
@@ -47,7 +47,7 @@ func TestDNS(t *testing.T) {
 		},
 		{
 			name:        "failure",
-			hostname:    "google.com",
+			hostname:    "google-fail.com",
```
Comment (smira) [inline internal/pkg/dns/dns_test.go:50]: I can't find the reason for test flakiness, but I did some cleanups here

**Review by frezbo — APPROVED** [review]
