### PR TITLE
fix: abort node watch on hostname change

### LINKED ISSUE #10163: Talos v1.9.2 nodes won't become ready, Kubernetes works
### Description

Essentially a continuation of https://github.com/siderolabs/talos/issues/9991, same observations as @bitfactory-henno-schooljan, new issue as requested. https://github.com/siderolabs/talos/commit/582064d9c latches onto a temporary node name (?), and `nodestatuses.kubernetes.talos.dev` is not populated anymore on any of the nodes. Talos shows the nodes as not ready while they are ready and operational in Kubernetes. `talosctl health` passes without issues. My nodes receive their addresses **and names** through DHCP.

### Logs

```yaml
# Configures cluster member discovery.
discovery:
    enabled: true # Enable the cluster membership discovery feature.
    # Configure registries used for cluster member discovery.
    registries:
        # Kubernetes registry uses Kubernetes API server to discover cluster members and stores additional information
        kubernetes:
            disabled: true # Disable Kubernetes discovery registry.
```

```
$ talosctl -n node-1 get machinestatus -oyaml
node: node-1
metadata:
    namespace: runtime
    type: MachineStatuses.runtime.talos.dev
    id: machine
    version: 14
    owner: runtime.MachineStatusController
    phase: running
    created: 2025-01-18T12:47:08Z
    updated: 2025-01-18T12:47:32Z
spec:
    stage: running
    status:
        ready: false
        unmetConditions:
            - name: nodeReady
              reason: node "node-1" status is not available yet
```

```
$ talosctl -n node-1 logs controller-runtime | egrep -i "nodestatus|talos-vcx-l96"
node-1: 2025-01-18T12:03:45.326Z DEBUG controller starting {"component": "controller-runtime", "controller": "k8s.NodeStatusController"}
node-1: 2025-01-18T12:03:48.286Z INFO setting hostname {"component": "controller-runtime", "controller": "network.HostnameSpecController", "hostname": "talos-vcx-l96", "domainname": ""}
node-1: 2025-01-18T12:03:48.287Z INFO setting hostname {"component": "controller-runtime", "controller": "network.HostnameSpecController", "hostname": "talos-vcx-l96", "domainname": ""}
node-1: 2025-01-18T12:03:50.289Z DEBUG starting node watcher {"component": "controller-runtime", "controller": "k8s.NodeStatusController", "nodename": "talos-vcx-l96"}
node-1: 2025-01-18T12:03:50.290Z DEBUG waiting for node cache sync {"component": "controller-runtime", "controller": "k8s.NodeStatusController"}
node-1: 2025-01-18T12:04:00.224Z ERROR controller failed {"component": "controller-runtime", "controller": "k8s.NodeApplyController", "error": "2 error(s) occurred:\n\terror getting node: nodes \"talos-vcx-l96\" is forbidden: User \"system:node:node-1\" cannot get resource \"nodes\" in API group \"\" at the cluster scope: node 'node-1' cannot read 'talos-vcx-l96', only its own Node object\n\terror getting node: client rate limiter Wait returned an error: rate: Wait(n=1) would exceed context deadline"}
```

So it seems that `AuthorizeNodeWithSelectors` is still stopping Talos, but this time it queries the completely wrong node. I presume `talos-vcx-l96` is the temporary name of the node before it receives the proper name through DHCP. The node status controller also latches onto this name (`starting node watcher {"component": "controller-runtime", "controller": "k8s.NodeStatusController", "nodename": "talos-vcx-l96"}`) and never receives the status (since the temporary node name is now gone), causing the readiness issue.

### Environment

- Talos version: [`talosctl version --nodes <problematic nodes>`]

```
Client:
        Tag:         v1.9.2
        SHA:         09758b3f
        Built:       
        Go version:  go1.23.4
        OS/Arch:     linux/amd64
Server:
        NODE:        node-1
        Tag:         v1.9.2
        SHA:         09758b3f
        Built:       
        Go version:  go1.23.4
        OS/Arch:     linux/amd64
        Enabled:     RBAC
```

- Kubernetes version: [`kubectl version --short`]

```
Client Version: v1.30.0
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.32.0
```

### PR DESCRIPTION
**Pull request by smira**
The method `WaitForCacheSync` might block for a long time, and looks like it can block forever if the nodename requested doesn't match the actual nodename.

Allow the wait to be aborted by running it in a goroutine, and notifying readiness of the watcher via the `notifyCh`.

Fixes #10163

### CODE REVIEW

**Review by frezbo — APPROVED** [review]

File: internal/app/machined/pkg/controllers/k8s/internal/nodewatch/nodewatch.go [hunk 1]
```diff
@@ -92,11 +92,25 @@ func (r *NodeWatcher) Watch(ctx context.Context, logger *zap.Logger) (<-chan str
...
-	informerFactory.WaitForCacheSync(ctx.Done())
+		result := informerFactory.WaitForCacheSync(ctx.Done())
 
-	logger.Debug("node cache sync done")
+		var synced bool
+
+		// result should contain a single entry
+		for _, v := range result {
+			synced = v
+		}
```
Comment (DmitriyMV) [inline internal/app/machined/pkg/controllers/k8s/internal/nodewatch/nodewatch.go:105]: This is probably

```suggestion
		for _, v := range result {
			synced |= v
		}
```
or

```suggestion
		for _, v := range result {
			synced &= v
		}
```

or even

```suggestion
		for _, v := range result {
			synced = v
			break
		}
```

But I'm not sure if there any reason to get random element of the map by iterating across the whole map.

File: internal/app/machined/pkg/controllers/k8s/node_status.go [hunk 2]
```diff
@@ -91,6 +91,8 @@ func (ctrl *NodeStatusController) Run(ctx context.Context, r controller.Runtime,
 			kubernetesClient = nil
 		}
 
+		watchErrors = 0
+		watchReady = false
```
Comment (DmitriyMV) [inline internal/app/machined/pkg/controllers/k8s/node_status.go:95]: I think you can remove `watchErrors = 0` below now after calling `closeWatcher()`.

**Review by DmitriyMV — APPROVED** [review]

File: internal/app/machined/pkg/controllers/k8s/internal/nodewatch/nodewatch.go (hunk 1 above)
Comment (smira) [reply internal/app/machined/pkg/controllers/k8s/internal/nodewatch/nodewatch.go:105]: if you read the comment above, the map contains a single element
