### PR TITLE
fix: fill serial using helpers

### LINKED ISSUE #11348: "serial" field in Talos is not populated (disks in QEMU VM hardware options do have it set)
### Description
In the VM configuration in Proxmox the `serial` attribute is properly displayed, but in the `talosctl get disks` output it is **not**. According to https://github.com/siderolabs/talos/issues/9951 the issue is fixed, but I am unsure if it should have been already released.

As you can see in the _disk details_ (below) output, the `serial` is actually included in the disk ID (e.g. the `storage` part in `/dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_storage`), but there does not seem to be a `serial` field with just `storage`. This would make it easier to use `diskSelector` on.

I copied/(re)designed a OpenTofu/Terraform script to deploy a single-node cluster on my server (see https://github.com/divStar/homelab/tree/master/modules/cluster) in case you need a reproducible.

I'll be enhancing my setup with a dedicated ephemeral (virtual) disk, but other than that I can certainly provide more information if necessary. Also if the issue suddenly resolves itself, I'll make sure to comment and close this ticket.

### Logs
```bash
$ talosctl --talosconfig ./output/talos-config.yaml get disks -n talos-ctrl-00
NODE            NAMESPACE   TYPE   ID      VERSION   SIZE     READ ONLY   TRANSPORT   ROTATIONAL   WWID   MODEL           SERIAL
talos-ctrl-00   runtime     Disk   loop0   2         4.1 kB   true                                                        
talos-ctrl-00   runtime     Disk   loop1   2         57 kB    true                                                        
talos-ctrl-00   runtime     Disk   loop2   2         475 kB   true                                                        
talos-ctrl-00   runtime     Disk   loop3   2         692 kB   true                                                        
talos-ctrl-00   runtime     Disk   loop4   2         4.1 kB   true                                                        
talos-ctrl-00   runtime     Disk   loop5   2         77 MB    true                                                        
talos-ctrl-00   runtime     Disk   sda     2         8.6 GB   false       virtio                          QEMU HARDDISK   
talos-ctrl-00   runtime     Disk   sdb     2         69 GB    false       virtio                          QEMU HARDDISK   
talos-ctrl-00   runtime     Disk   sr0     2         4.2 MB   false       sata                            QEMU DVD-ROM
```

<details>
<summary>More detailed disks output</summary>

```bash
igvo@~/Documents/homelab-tofu/modules/cluster (feature/zitadel) talosctl --talosconfig ./output/talos-config.yaml get disks -o yaml -n talos-ctrl-00                                                                                   ✭ ✱
node: talos-ctrl-00
metadata:
    namespace: runtime
    type: Disks.block.talos.dev
    id: loop0
    version: 2
    owner: block.DisksController
    phase: running
    created: 2025-07-06T14:42:47Z
    updated: 2025-07-06T14:43:05Z
spec:
    dev_path: /dev/loop0
    size: 4096
    pretty_size: 4.1 kB
    io_size: 512
    sector_size: 512
    readonly: true
    cdrom: false
    bus_path: /virtual
    sub_system: /sys/class/block
    symlinks:
        - /dev/disk/by-diskseq/9
        - /dev/disk/by-loop-inode/0:2-15
        - /dev/disk/by-loop-ref/4.sqsh
---
node: talos-ctrl-00
metadata:
    namespace: runtime
    type: Disks.block.talos.dev
    id: loop1
    version: 2
    owner: block.DisksController
    phase: running
    created: 2025-07-06T14:42:47Z
    updated: 2025-07-06T14:43:05Z
spec:
    dev_path: /dev/loop1
    size: 57344
    pretty_size: 57 kB
    io_size: 512
    sector_size: 512
    readonly: true
    cdrom: false
    bus_path: /virtual
    sub_system: /sys/class/block
    symlinks:
        - /dev/disk/by-diskseq/10
        - /dev/disk/by-loop-inode/0:2-14
        - /dev/disk/by-loop-ref/3.sqsh
---
node: talos-ctrl-00
metadata:
    namespace: runtime
    type: Disks.block.talos.dev
    id: loop2
    version: 2
    owner: block.DisksController
    phase: running
    created: 2025-07-06T14:42:47Z
    updated: 2025-07-06T14:43:05Z
spec:
    dev_path: /dev/loop2
    size: 475136
    pretty_size: 475 kB
    io_size: 512
    sector_size: 512
    readonly: true
    cdrom: false
    bus_path: /virtual
    sub_system: /sys/class/block
    symlinks:
        - /dev/disk/by-diskseq/11
        - /dev/disk/by-loop-inode/0:2-13
        - /dev/disk/by-loop-ref/2.sqsh
---
node: talos-ctrl-00
metadata:
    namespace: runtime
    type: Disks.block.talos.dev
    id: loop3
    version: 2
    owner: block.DisksController
    phase: running
    created: 2025-07-06T14:42:47Z
    updated: 2025-07-06T14:43:05Z
spec:
    dev_path: /dev/loop3
    size: 692224
    pretty_size: 692 kB
    io_size: 512
    sector_size: 512
    readonly: true
    cdrom: false
    bus_path: /virtual
    sub_system: /sys/class/block
    symlinks:
        - /dev/disk/by-diskseq/12
        - /dev/disk/by-loop-inode/0:2-12
        - /dev/disk/by-loop-ref/1.sqsh
---
node: talos-ctrl-00
metadata:
    namespace: runtime
    type: Disks.block.talos.dev
    id: loop4
    version: 2
    owner: block.DisksController
    phase: running
    created: 2025-07-06T14:42:47Z
    updated: 2025-07-06T14:43:05Z
spec:
    dev_path: /dev/loop4
    size: 4096
    pretty_size: 4.1 kB
    io_size: 512
    sector_size: 512
    readonly: true
    cdrom: false
    bus_path: /virtual
    sub_system: /sys/class/block
    symlinks:
        - /dev/disk/by-diskseq/13
        - /dev/disk/by-loop-inode/0:2-11
        - /dev/disk/by-loop-ref/0.sqsh
---
node: talos-ctrl-00
metadata:
    namespace: runtime
    type: Disks.block.talos.dev
    id: loop5
    version: 2
    owner: block.DisksController
    phase: running
    created: 2025-07-06T14:42:47Z
    updated: 2025-07-06T14:43:05Z
spec:
    dev_path: /dev/loop5
    size: 77250560
    pretty_size: 77 MB
    io_size: 512
    sector_size: 512
    readonly: true
    cdrom: false
    bus_path: /virtual
    sub_system: /sys/class/block
    symlinks:
        - /dev/disk/by-diskseq/14
        - /dev/disk/by-loop-inode/0:2-10
        - /dev/disk/by-loop-ref/\x2frootfs.sqsh
---
node: talos-ctrl-00
metadata:
    namespace: runtime
    type: Disks.block.talos.dev
    id: sda
    version: 2
    owner: block.DisksController
    phase: running
    created: 2025-07-06T14:42:48Z
    updated: 2025-07-06T14:43:05Z
spec:
    dev_path: /dev/sda
    size: 8589934592
    pretty_size: 8.6 GB
    io_size: 512
    sector_size: 512
    readonly: false
    cdrom: false
    model: QEMU HARDDISK
    modalias: scsi:t-0x00
    bus_path: /pci0000:00/0000:00:1e.0/0000:05:04.0/0000:09:01.0/virtio8/host6/target6:0:0/6:0:0:0
    sub_system: /sys/class/block
    transport: virtio
    symlinks:
        - /dev/disk/by-diskseq/15
        - /dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_boot
        - /dev/disk/by-path/pci-0000:09:01.0-scsi-0:0:0:0
---
node: talos-ctrl-00
metadata:
    namespace: runtime
    type: Disks.block.talos.dev
    id: sdb
    version: 2
    owner: block.DisksController
    phase: running
    created: 2025-07-06T14:42:57Z
    updated: 2025-07-06T14:43:05Z
spec:
    dev_path: /dev/sdb
    size: 68719476736
    pretty_size: 69 GB
    io_size: 512
    sector_size: 512
    readonly: false
    cdrom: false
    model: QEMU HARDDISK
    modalias: scsi:t-0x00
    bus_path: /pci0000:00/0000:00:1e.0/0000:05:04.0/0000:09:02.0/virtio9/host7/target7:0:0/7:0:0:1
    sub_system: /sys/class/block
    transport: virtio
    symlinks:
        - /dev/disk/by-diskseq/18
        - /dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_storage
        - /dev/disk/by-path/pci-0000:09:02.0-scsi-0:0:0:1
---
node: talos-ctrl-00
metadata:
    namespace: runtime
    type: Disks.block.talos.dev
    id: sr0
    version: 2
    owner: block.DisksController
    phase: running
    created: 2025-07-06T14:42:48Z
    updated: 2025-07-06T14:43:05Z
spec:
    dev_path: /dev/sr0
    size: 4194304
    pretty_size: 4.2 MB
    io_size: 2048
    sector_size: 2048
    readonly: false
    cdrom: true
    model: QEMU DVD-ROM
    modalias: scsi:t-0x05
    bus_path: /pci0000:00/0000:00:1f.2/ata2/host1/target1:0:0/1:0:0:0
    sub_system: /sys/class/block
    transport: sata
    symlinks:
        - /dev/disk/by-diskseq/17
        - /dev/disk/by-id/ata-QEMU_DVD-ROM_QM00003
        - /dev/disk/by-path/pci-0000:00:1f.2-ata-2
        - /dev/disk/by-path/pci-0000:00:1f.2-ata-2.0
```
</details>

Image

### Environment

- Talos version: [`talosctl version --nodes <problematic nodes>`]
```
Client:
	Tag:         v1.10.1
	SHA:         52269e81
	Built:       
	Go version:  go1.24.2
	OS/Arch:     darwin/arm64
Server:
	NODE:        talos-ctrl-00
	Tag:         v1.10.4
	SHA:         3c119bf8
	Built:       
	Go version:  go1.24.4
	OS/Arch:     linux/amd64
	Enabled:     RBAC
```
- Kubernetes version: [`kubectl version`]
```
Client Version: v1.33.0
Kustomize Version: v5.6.0
Server Version: v1.33.0
```
- Platform: Proxmox VE 8.4.1

### PR DESCRIPTION
**Pull request by shanduur**
Use `udev` helpers to try to extract serial information, in case it is missing. 

Fixes #11348

### CODE REVIEW

File: internal/app/machined/pkg/controllers/block/disks.go [hunk 1]
```diff
@@ -247,3 +261,62 @@ func (ctrl *DisksController) analyzeBlockDevice(
...
+	env := map[string]string{}
+
+	scanner := bufio.NewScanner(r)
+	for scanner.Scan() {
+		line := scanner.Text()
+		if line == "" || strings.HasPrefix(line, "#") {
+			continue
+		}
+
+		parts := strings.SplitN(line, "=", 2)
```
Comment (smira) [inline internal/app/machined/pkg/controllers/block/disks.go]: nit, we can do more modern (and more allocation-friendly) `strings.Cut`

```suggestion
		key, value, ok := strings.Cut(line, "=")
		if !ok {
		   continue
		}
```
