### PR TITLE
fix: restore previous disk serial fetching

### LINKED ISSUE #9951: Missing SerialNumber for Disks on QEMU Nodes in Talos 1.8.3
## Bug Report

We are hosting Talos cluster on virtual machines and bare metal servers. When migrating to Talos 1.8, we noticed that the disks Serial Number are not displayed anymore when running the command `talosctl disks -n <node-name>`. This behavior is observed **only** on virtual machines (tested on OVH Openstack and Proxmox).

Expected behavior (Current behavior on Talos 1.7):

```bash
NODE     DEV        MODEL   SERIAL                 TYPE   UUID   WWID   MODALIAS                    NAME   SIZE    BUS_PATH                            SUBSYSTEM          READ_ONLY   SYSTEM_DISK
node-1   /dev/vda   -       -                      HDD    -      -      virtio:d00000002v00001AF4   -      54 GB   /pci0000:00/0000:00:04.0/virtio1/   /sys/class/block               *
node-1   /dev/vdb   -       6c03fee7-62d6-4622-a   HDD    -      -      virtio:d00000002v00001AF4   -      64 GB   /pci0000:00/0000:00:06.0/virtio3/   /sys/class/block
node-1   /dev/vdc   -       68b44103-d642-42aa-a   HDD    -      -      virtio:d00000002v00001AF4   -      64 GB   /pci0000:00/0000:00:07.0/virtio4/   /sys/class/block
node-1   /dev/vdd   -       993f9c2f-af83-4cba-b   HDD    -      -      virtio:d00000002v00001AF4   -      64 GB   /pci0000:00/0000:00:08.0/virtio5/   /sys/class/block
```

Actual behavior (on a Talos 1.8 cluster):

```bash
NODE   DEV          MODEL          SERIAL   TYPE      UUID   WWID   MODALIAS                    NAME   SIZE     BUS_PATH                                                  SUBSYSTEM          READ_ONLY   SYSTEM_DISK
w1     /dev/sr0     QEMU DVD-ROM   -        CD        -      -      scsi:t-0x05                 -      819 kB   /pci0000:00/0000:00:01.1/ata1/host0/target0:0:0/0:0:0:0   /sys/class/block
w1     /dev/vda     -              -        HDD       -      -      virtio:d00000002v00001AF4   -      54 GB    /pci0000:00/0000:00:04.0/virtio1                          /sys/class/block               *
w1     /dev/vdb     -              -        HDD       -      -      virtio:d00000002v00001AF4   -      64 GB    /pci0000:00/0000:00:06.0/virtio3                          /sys/class/block
w1     /dev/vdc     -              -        HDD       -      -      virtio:d00000002v00001AF4   -      64 GB    /pci0000:00/0000:00:07.0/virtio4                          /sys/class/block
w1     /dev/vdd     -              -        HDD       -      -      virtio:d00000002v00001AF4   -      64 GB    /pci0000:00/0000:00:08.0/virtio5                          /sys/class/block
```

The new `talosctl get disks` doesn't return the Serial Number at all (no field for it).

Steps to reproduce:
- Deploy a Talos 1.8 node on a virtual machine (OVH Openstack, Proxmox, etc.)
- Run the command `talosctl disks -n <node-name>`
- The Serial Number field is empty
- Deploy a bare metal server with Talos 1.8
- Run the command `talosctl disks -n <node-name>`
- The Serial Number field is displayed correctly

### Environment

- Talos version:
```bash
Client:
	Tag:         v1.8.3
	SHA:         6494aced
	Built:
	Go version:  go1.22.9
	OS/Arch:     darwin/arm64
Server:
	NODE:        w1
	Tag:         v1.8.3
	SHA:         6494aced
	Built:
	Go version:  go1.22.9
	OS/Arch:     linux/amd64
	Enabled:     RBAC
```

- Platform: OVH Openstack

### PR DESCRIPTION
**Pull request by smira**
See https://github.com/siderolabs/go-blockdevice/pull/119

Fixes #9951

### CODE REVIEW

File: internal/app/machined/pkg/controllers/network/cmdline_test.go [hunk 1]
```diff
@@ -166,6 +166,28 @@ func (suite *CmdlineSuite) TestParse() {
 				},
 			},
 		},
+		{
+			name:    "another config",
```
Comment (smira) [inline internal/app/machined/pkg/controllers/network/cmdline_test.go:170]: totally unrelated, but another unit-test won't hurt ;)

**Review by utkuozdemir — APPROVED** [review]

**Review by frezbo — APPROVED** [review]

**Review by dsseng — APPROVED** [review]
