### PR TITLE
fix: put correct capacity to the ovf

### LINKED ISSUE #7627: Talos v1.5.0 failing to deploy from ova template
### Description
Hello! When I try to deploy ova, the template wants to allocate 8192.0 TB on the datastore and then fails.

### Logs
`The operation failed due to File [nfs_default_1] talos-vmware-1.5.0/talos-vmware-1.5.0.vmdk is larger than the maximum size supported by datastore 'nfs_default_1' 
`
### Environment

- Talos version: 1.5.0
- Kubernetes version: [`kubectl version --short`]
- Platform: VMware

### PR DESCRIPTION
**Pull request by smira**
With the refactoring to 1.5, the confusion between bytes and megabytes introduced this bug.

Fixes #7627

### CODE REVIEW

**Review by TimJones — APPROVED** [review]

File: pkg/imager/ova/ova.go [hunk 1]
```diff
@@ -249,7 +249,7 @@ func renderOVF(name string, size, capacity int64) (string, error) {
 	}{
 		VMDK:     name + ".vmdk",
 		Size:     size,
-		Capacity: capacity,
+		Capacity: capacity / (1 << 20),
```
Comment (frezbo) [inline pkg/imager/ova/ova.go:252]: should we set this in `capacity` variable then, or is only applicable to OVA,? I guess `Capacity` field expects a MB value?

**Review by frezbo — APPROVED** [review]

File: pkg/imager/ova/ova.go (hunk 1 above)
Comment (smira) [reply pkg/imager/ova/ova.go:252]: it's just the way we build the XML template... we say in the XML that it's in MiB. I could change the template, but I'm less sure it will work :-D

Comment (smira) [reply pkg/imager/ova/ova.go:252]: I will probably rename the argument to `diskSize` to match other usecases

Comment (frezbo) [reply pkg/imager/ova/ova.go]: yeh, just a comment saying it expects MiB is fine for future reference

Comment (smira) [reply pkg/imager/ova/ova.go]: renamed to make things less confusing

**Review by frezbo — APPROVED** [review]
