### PR TITLE
fix: invalid versions check in talos-bundle

### LINKED ISSUE #12471: `talosctl image talos-bundle` incorrectly handles maximum version
### Description

The command `talosctl image talos-bundle v1.12.0` fails with:
```
invalid argument "v1.12.0" for "talosctl image talos-bundle": tag for the bundle must be within range "v1.11.0-alpha.0" - "v1.12.0"
```
However, `v1.12.0` is within the range

### Root cause

The version validation uses `GTE` for minimum version but only `LT` for the maximum version, when it should be `LTE`
https://github.com/siderolabs/talos/blob/48d242918bc97e6a01434bee6fcdcfa735fd1f5a/cmd/talosctl/cmd/talos/image.go#L213

### Environment

Talosctl:
* Tag: v1.12.0
* SHA: ac91ade2
* Built: 
* Go version: go1.25.5
* OS/Arch: linux/amd64

### PR DESCRIPTION
**Pull request by shanduur**
Fixes #12471

Signed-off-by: Mateusz Urbanek <mateusz.urbanek@siderolabs.com>

### CODE REVIEW

**Review by smira — APPROVED** [review]
should we have a simple integration/cli test where we run this command with current version?

File: cmd/talosctl/cmd/talos/image.go [hunk 1]
```diff
@@ -198,6 +198,12 @@ var imageSourceBundleCmd = &cobra.Command{
 				panic(err) // panic, this should never happen
 			}
 
+			maximumVersion.Patch = 0
```
Comment (frezbo) [inline cmd/talosctl/cmd/talos/image.go:201]: we could just return like in quirks https://github.com/siderolabs/talos/blob/main/pkg/machinery/imager/quirks/quirks.go#L16

Comment (shanduur) [reply cmd/talosctl/cmd/talos/image.go:201]: Quirks are `imager` specific, I don't think this belongs there :/

**Review by frezbo — APPROVED** [review]
