### PR TITLE
fix: reload trusted CA list when client is recreated

### LINKED ISSUE #5652: Machine configuration intermittently recognizes custom CA certificate
### Description
When I create a new cluster, the cluster config has a custom cni with a url to a private gitlab repo which uses a custom CA. In the machine config I append my custom CA to /etc/ssl/certs/ca-certificates. But, when my new CP node boots up for the first time I continuously get x509 errors when it's trying to pull the cni manifest. After I reboot the server after the initial config loads then it's able to grab the manifests.
### Logs
TBD, logs are in an air-gapped environment which I'll work on pulling over. 
### Environment

- Talos version: v1.0.5
- Kubernetes version: 1.23.6
- Platform: Sidero Metal

### PR DESCRIPTION
**Pull request by smira**
Fixes #5652

This reworks and unifies HTTP client/transport management in Talos:

* cleanhttp is used everywhere consistently
* DefaultClient is using pooled client, other clients use regular
  transport
* like before, Proxy vars are inspected on each request (but now
  consistently)
* manifest download functions now recreate the client on each run to
  pick up latest changes
* system CA list is picked up from a fixed locations, and supports
  reloading on changes

Signed-off-by: Andrey Smirnov <andrey.smirnov@talos-systems.com>

---
This change is [Reviewable](https://reviewable.io/reviews/siderolabs/talos/5733)

### CODE REVIEW

**Comment by smira** [comment]
Draft, as needs more testing, I will do that once I get back to work.

**Comment by smira** [comment]
I added a tool to test things like this - HTTP proxy, self-signed (or custom) CAs, etc.

File: pkg/download/download.go [hunk 1]
```diff
@@ -214,8 +220,3 @@ func download(req *http.Request, dlOpts *downloadOptions) (data []byte, err erro
 
 	return data, nil
 }
-
-func init() {
```
Comment (frezbo) [inline pkg/download/download.go:218]: :+1: on removing `init`

File: website/content/v1.2/advanced/developing-talos.md [hunk 2]
```diff
@@ -233,3 +233,69 @@ The IP address `172.20.0.2` is the address of the Talos node, and port `:9982` d
 - 9981: `apid`
 - 9982: `machined`
 - 9983: `trustd`
+
+## Testing Air-gapped Environments
```
Comment (frezbo) [inline website/content/v1.2/advanced/developing-talos.md:237]: :cool:

**Review by frezbo — APPROVED** [review]
:cool:
