### PR TITLE
fix: avoid nil-pointer-panic in `RegistriesConfigController`

### LINKED ISSUE #9912: Segfault when installing talos v1.9.0-beta.0 on bare metal
### Description
When hitting `talosctl apply-config -f ... --insecure --nodes ...` against my bare metal machine in maintenance mode I almost immediately get a segfault. 

### Logs
talos19_segfault

### Environment

- Talos version: v1.9.0-beta.0 (from image factory)
- Platform: amd64, secureboot

### PR DESCRIPTION
**Pull request by DmitriyMV**
One billion dollar mistake strikes again. Increase code coverage.

Closes #9912

### CODE REVIEW

**Review by smira — APPROVED** [review]

File: pkg/machinery/config/types/v1alpha1/v1alpha1_validation.go [hunk 1]
```diff
@@ -348,6 +348,18 @@ func (c *Config) Validate(mode validation.RuntimeMode, options ...validation.Opt
 		}
 	}
 
+	for key, val := range c.MachineConfig.MachineRegistries.RegistryConfig {
```
Comment (frezbo) [inline pkg/machinery/config/types/v1alpha1/v1alpha1_validation.go:351]: probably also add a validation test to the existing validation tests

**Review by frezbo — APPROVED** [review]
