### PR TITLE
fix: improve talosctl completion

### LINKED ISSUE #6646: cli: talosctl get (without argument) does not autocomplete in 1.3.0
## Bug Report
`talosctl get` (without arguments) does not autocomplete. It does work with `talosctl get a`

This worked in previous versions. And i use it a lot...

### Description
I see most code was rewritten here:
https://github.com/siderolabs/talos/commit/9baca49662ae3b542752cb797eaf2c9956149902#diff-a262b85cfb10d7bf31e9c80273372fb9f0308e3bd7ec7c51053f568d42075e7e

I will have a look later this week to try to fix it....

### Logs
```sh
$ talosctl __complete get
get	Get a specific resource or list of resources (use 'talosctl get rd' to see all available resource types).
:4
Completion ended with directive: ShellCompDirectiveNoFileComp
```

### Environment

- Talos version: 1.3.0
- Kubernetes version:  1.25
- Platform:

### PR DESCRIPTION
**Pull request by smira**
This got broken with a sequence of changes related to not unmarshalling resources when using `get`.

Rewrite the completion to be more straightforward and use easier methods.

Make shell completion work even when `nodes` are not set.

Fixes #6646

Signed-off-by: Andrey Smirnov <andrey.smirnov@talos-systems.com>

### CODE REVIEW

**Review by Unix4ever — APPROVED** [review]

File: cmd/talosctl/cmd/talos/get.go [hunk 1]
```diff
@@ -230,45 +224,61 @@ func aggregateEvents(ctx context.Context, outCh chan<- nodeAndEvent, watchCh <-c
...
+			}
+
+			result = append(result, iter.Value().Metadata().ID())
 		}
 
-		if !hasAliases {
-			return nil
+		return nil
+	}) != nil {
+		return nil, cobra.ShellCompDirectiveError
```
Comment (nberlee) [inline cmd/talosctl/cmd/talos/get.go:247]: Tested it, works great.... 
Minor nit, please add `| cobra.ShellCompDirectiveNoFileComp` here. In the event of an error (for example a timeout), it should not autocomplete with files

**Review by frezbo — APPROVED** [review]
