### PR TITLE
fix: update etcd certificates when node addresses changes

### LINKED ISSUE #6110: etcd tls does not match any of DNSNames
### Description

Etcd peer (client too) certificate does not have listen IPs.

machine-config:
```yaml
cluster:
  etcd:
    advertisedSubnets:
      - 172.16.0.0/12
    listenSubnets:
      - 172.16.0.0/12
```
### Logs

control-plane-1
```
172.16.0.11: {"level":"warn","ts":"2022-08-16T14:30:26.289Z","caller":"rafthttp/probing_status.go:68","msg":"prober detected unhealthy status","round-tripper-name":"ROUND_TRIPPER_RAFT_MESSAGE","remote-peer-id":"bac29e825bf921c2","rtt":"0s","error":"x509: certificate is valid for 10.197.230.1, 2001:bc8:1202:800::1, not 172.16.0.12"}
172.16.0.11: {"level":"warn","ts":"2022-08-16T14:30:26.302Z","caller":"rafthttp/probing_status.go:68","msg":"prober detected unhealthy status","round-tripper-name":"ROUND_TRIPPER_SNAPSHOT","remote-peer-id":"bac29e825bf921c2","rtt":"0s","error":"x509: certificate is valid for 10.197.230.1, 2001:bc8:1202:800::1, not 172.16.0.12"}
172.16.0.11: {"level":"warn","ts":"2022-08-16T14:30:28.857Z","caller":"embed/config_logging.go:160","msg":"rejected connection","remote-addr":"172.16.0.12:56054","server-name":"","ip-addresses":["10.197.230.1","2001:bc8:1202:800::1"],"dns-names":["controlplane-2"],"error":"tls: \"172.16.0.12\" does not match any of DNSNames [\"controlplane-2\"] (lookup controlplane-2 on 1.1.1.1:53: no such host)"}
```

control-plane-2
```
172.16.0.12: {"level":"info","ts":"2022-08-16T14:32:31.210Z","caller":"embed/etcd.go:139","msg":"configuring client listeners","listen-client-urls":["https://172.16.0.12:2379","https://[::1]:2379"]}
172.16.0.12: {"level":"info","ts":"2022-08-16T14:32:31.211Z","caller":"embed/etcd.go:308","msg":"starting an etcd server","etcd-version":"3.5.4","git-sha":"08407ff76","go-version":"go1.16.15","go-os":"linux","go-arch":"amd64","max-cpu-set":3,"max-cpu-available":3,"member-initialized":false,"name":"controlplane-2","data-dir":"/var/lib/etcd","wal-dir":"","wal-dir-dedicated":"","member-dir":"/var/lib/etcd/member","force-new-cluster":false,"heartbeat-interval":"100ms","election-timeout":"1s","initial-election-tick-advance":true,"snapshot-count":100000,"snapshot-catchup-entries":5000,"initial-advertise-peer-urls":["https://172.16.0.12:2380"],"listen-peer-urls":["https://172.16.0.12:2380"],"advertise-client-urls":["https://172.16.0.12:2379"],"listen-client-urls":["https://172.16.0.12:2379","https://[::1]:2379"],"listen-metrics-urls":[],"cors":["*"],"host-whitelist":["*"],"initial-cluster":"controlplane-1=https://172.16.0.11:2380,controlplane-2=https://172.16.0.12:2380","initial-cluster-state":"existing","initial-cluster-token":"etcd-cluster","quota-size-bytes":2147483648,"pre-vote":true,"initial-corrupt-check":true,"corrupt-check-time-interval":"0s","auto-compaction-mode":"periodic","auto-compaction-retention":"0s","auto-compaction-interval":"0s","discovery-url":"","discovery-proxy":"","downgrade-check-interval":"5s"}
172.16.0.12: {"level":"info","ts":"2022-08-16T14:32:31.212Z","caller":"etcdserver/backend.go:81","msg":"opened backend db","path":"/var/lib/etcd/member/snap/db","took":"848.957µs"}
172.16.0.12: {"level":"warn","ts":"2022-08-16T14:32:31.247Z","caller":"embed/config_logging.go:169","msg":"rejected connection","remote-addr":"172.16.0.11:35026","server-name":"","error":"remote error: tls: bad certificate"}
```

### Environment

- Talos version: v1.2.0-beta.0

### PR DESCRIPTION
**Pull request by smira**
Fixes #6110

I somehow missed the fact that etcd certs were not made fully reactive
to node address changes (I wrongly assume it was already the fact).

This PR refactors etcd certificate generation process to be
resource-based and introduces unit-tests for the controller.

Signed-off-by: Andrey Smirnov <andrey.smirnov@talos-systems.com>

### CODE REVIEW

File: internal/app/machined/pkg/controllers/secrets/etcd_test.go [hunk 1]
```diff
@@ -0,0 +1,132 @@
...
+
+		suite.Assert().Equal("talos", adminCert.Subject.CommonName)
+
+		kubeAPICert, err := etcdCerts.EtcdAPIServer.GetCert()
+		suite.Require().NoError(err)
+
+		suite.Assert().Empty(kubeAPICert.DNSNames)
+		suite.Assert().Empty(kubeAPICert.IPAddresses)
+
+		suite.Assert().Equal("kube-apiserver", kubeAPICert.Subject.CommonName)
```
Comment (frezbo) [inline internal/app/machined/pkg/controllers/secrets/etcd_test.go:128]: shouldn't we add a test where we update the node addresses and see the certs sans got updated?

Comment (smira) [reply internal/app/machined/pkg/controllers/secrets/etcd_test.go:128]: yep, I can do that... should be fairly easy

Comment (smira) [reply internal/app/machined/pkg/controllers/secrets/etcd_test.go]: done

**Review by Unix4ever — APPROVED** [review]
