### PR TITLE
fix: oracle integration fixes

### LINKED ISSUE #7528: Incorrect health check in Oracle Cloud Documentation
### Description
https://www.talos.dev/v1.4/talos-guides/install/cloud-platforms/oracle/#create-a-load-balancer
It is stated here that the control-plane health checker should be using https check on port 6443, and get status response 200.
But since the network load balancer is not authed, that would respond as 401.

This should probably be changed to a TCP check on the port instead.

https://github.com/siderolabs/talos/blob/ffa48ac80359c9d748d02a2a3a95eaa7ef95d20a/website/content/v1.4/talos-guides/install/cloud-platforms/oracle.md?plain=1#L72

### Environment

- Talos version: 1.4.6
- Kubernetes version: 1.27.6
- Platform: Oracle Cloud

### PR DESCRIPTION
**Pull request by sergelogvinov**
# Pull Request

## What? (description)

Update oracle platform:

* Set static gateway IPv6 if it possible. Some cni do not work properly with ipv6, so we will fix it. (We already did the same in gcp/azure)
* Disable Talos dashboard. Oracle cloud does not have screen interface.

close #7528

## Acceptance

Please use the following checklist:

- [ ] you linked an issue (if applicable)
- [ ] you included tests (if applicable)
- [ ] you ran conformance (`make conformance`)
- [x] you formatted your code (`make fmt`)
- [x] you linted your code (`make lint`)
- [ ] you generated documentation (`make docs`)
- [x] you ran unit-tests (`make unit-tests`)

> See `make help` for a description of the available targets.

### CODE REVIEW

File: internal/app/machined/pkg/runtime/v1alpha1/platform/oracle/oracle.go [hunk 1]
```diff
@@ -61,18 +64,38 @@ func (o *Oracle) ParseMetadata(interfaceAddresses []NetworkConfig, metadata *Met
...
 	for idx, iface := range interfaceAddresses {
-		ipv6 := iface.Ipv6SubnetCidrBlock != "" && iface.Ipv6VirtualRouterIP != ""
+		ifname := fmt.Sprintf("eth%d", idx)
 
-		if ipv6 {
+		if iface.Ipv6SubnetCidrBlock != "" && iface.Ipv6VirtualRouterIP != "" {
 			networkConfig.Operators = append(networkConfig.Operators, network.OperatorSpecSpec{
 				Operator:  network.OperatorDHCP6,
-				LinkName:  fmt.Sprintf("eth%d", idx),
+				LinkName:  ifname,
```
Comment (smira) [inline internal/app/machined/pkg/runtime/v1alpha1/platform/oracle/oracle.go:72]: just curious, are we using DHCP6 instead of static IP for a reason?

Comment (sergelogvinov) [reply internal/app/machined/pkg/runtime/v1alpha1/platform/oracle/oracle.go:72]: Metadata has static IPv4 and IPv6 already (it did not have one year before)

**Review by smira — APPROVED** [review]
