### PR TITLE
fix: set correct (1 year) talosconfig expiration

### LINKED ISSUE #7698: "talosctl config info" shows not expected cert expire time
## Bug Report

in the documentation I read that the talosconfig certificate ist valid for 365 days.
https://www.talos.dev/v1.5/talos-guides/configuration/managing-pki/#renewing-an-expired-administrator-certificate

But the result of the following command shows 10 years:

```
talosctl config info

Current context:   testing
Nodes:        not defined
Endpoints:      163.149.62.181
Roles:        os:admin
Certificate expires: 10 years from now (2033-08-29)
```

### Environment

- Talos version: 1.5.1

### PR DESCRIPTION
**Pull request by smira**
Fixes #7698

Also fix `talosctl config info` for `talosconfig` without a client certificate (e.g. Omni-generated one).

### CODE REVIEW

File: pkg/machinery/config/generate/secrets/bundle.go [hunk 1]
```diff
@@ -351,6 +351,6 @@ func (bundle *Bundle) GenerateTalosAPIClientCertificate(roles role.Set) (*x509.P
 		bundle.Clock.Now(),
 		bundle.Certs.OS,
 		roles,
-		CAValidityTime,
+		constants.TalosAPIDefaultCertificateValidityDuration,
```
Comment (smira) [inline pkg/machinery/config/generate/secrets/bundle.go:354]: this is the main fix
