### PR TITLE
fix: mount selinuxfs only when SELinux is enabled

### LINKED ISSUE #10083: KubeVirt does not work with Talos Linux 1.9
### Logs

virt-handler reports an error during VM creation:
```
failed to configure vmi network: setup failed, err: Critical network error: could not retrieve pid 199735 selinux label: getxattr /proc/199735/attr/current: operation not supported
```

this is happening because of selinux enabled:

```
cat /sys/fs/selinux/enforce
0
```

code:
- https://github.com/kubevirt/kubevirt/blob/9120e62feedcb842be595a9d1069e305c07d01b9/pkg/virt-handler/selinux/context_executor.go#L112
- https://github.com/kubevirt/kubevirt/blob/9120e62feedcb842be595a9d1069e305c07d01b9/cmd/virt-chroot/selinux.go#L102

### Environment

- Talos version: v1.9.1
- Kubernetes version: v1.30.3
- Platform: Cozystack

I tried to disable selinux using machineconfig:

```yaml
machine:
    install:
        extraKernelArgs:
        - -selinux
```

and 

```yaml
machine:
    install:
        extraKernelArgs:
        - selinux=0
```
and running `talosctl upgrade` commad, but it had no effect

Talos Linux 1.8 have no `/sys/fs/selinux/enforce` so this check returns false:
- https://github.com/kubevirt/kubevirt/blob/9120e62feedcb842be595a9d1069e305c07d01b9/cmd/virt-chroot/selinux.go#L27

### PR DESCRIPTION
**Pull request by dsseng**
Having selinuxfs mounted might confuse some software, as conventional Linux systems do not have selinuxfs mounted when SELinux is disabled and no policy is loaded.

Fixes #10083

Signed-off-by: Dmitry Sharshakov <dmitry.sharshakov@siderolabs.com>

### CODE REVIEW

File: internal/pkg/mount/v2/pseudo.go [hunk 1]
```diff
@@ -48,7 +49,7 @@ func PseudoSubMountPoints() Points {
 		)
 	}
 
-	if _, err := os.Stat("/sys/fs/selinux"); err == nil {
+	if _, err := os.Stat("/sys/fs/selinux"); err == nil && selinux.IsEnabled() {
```
Comment (frezbo) [inline internal/pkg/mount/v2/pseudo.go:52]: I guess we can then drop the `/sys/fs/selinux` check then?

Comment (frezbo) [reply internal/pkg/mount/v2/pseudo.go:52]: I thought we did the `/sys/fs/selinux` only appeared when `selinux=1` was set

Comment (dsseng) [reply internal/pkg/mount/v2/pseudo.go:52]: Did we add that check for cases like when apparmor is enabled and selinux is then disabled? Then perhaps yes, we can drop that check

**Review by frezbo — APPROVED** [review]

File: internal/pkg/mount/v2/pseudo.go (hunk 1 above)
Comment (frezbo) [reply internal/pkg/mount/v2/pseudo.go]: > Did we add that check for cases like when apparmor is enabled and selinux is then disabled?

I believe so

**Review by kvaps — APPROVED** [review]
