### PR TITLE
fix: shorten VLAN link names to fit into the limit of 15 characters

### LINKED ISSUE #7679: Can't create vlans, got error, possibly due to predictable network interface
## Bug Report

I'm trying to add vlans, and I got an error in the console:

```
[talos] controller failed {"component": "controller-runtime", "controller": "network.LinkSpecController", "error": "2 errors occurred:\n\t* error creating logical link \"enx72469011805a.11\": netlink receive: numerical result out of range\n\t* error creating logical link \"enx72469011805a.24\": netlink receive: numerical result out of range\n\n"}
```

### Description

Excerpt from my talos configuration:

```
machine:
    network:
        interfaces:
            - deviceSelector:
                hardwareAddr: 5a:31:8e:74:fd:85
              addresses:
                - 192.168.[REDACTED]/24
              routes:
                - network: 0.0.0.0/0
                  gateway: 192.168.[REDACTED]
              vlans:
                - addresses:
                    - 192.168.[REDACTED]/24
                  dhcp: false
                  vlanId: 11
                  mtu: 1500
                - addresses:
                    - 192.168.[REDACTED]/24
                  dhcp: false
                  vlanId: 24
                  mtu: 1500
        nameservers:
            - 192.168.[REDACTED]
            - 192.168.[REDACTED]
...
```

I created a pod with `hostNetwork: true` and installed iproute2 (poor man talos ssh/bash). Tried to create manually. Looks like predictable network interface causes some naming issue:

```
talos02:/# ip link add link enx72469011805a name enx72469011805a.11 type vlan id 11
Error: argument "enx72469011805a.11" is wrong: "name" not a valid ifname
talos02:/# ip link add link enx72469011805a name vlan11 type vlan id 11
talos02:/# ip link sh dev vlan11
22: vlan11@enx72469011805a: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN mode DEFAULT group default qlen 1000
    link/ether 72:46:90:11:80:5a brd ff:ff:ff:ff:ff:ff
```

### Environment

- Talos version:
```
Client:
        Tag:         v1.5.1
        SHA:         40a22cdf
        Built:
        Go version:  go1.20.7
        OS/Arch:     linux/amd64
Server:
        NODE:        192.168.[REDACTED]
        Tag:         v1.5.1
        SHA:         40a22cdf
        Built:
        Go version:  go1.20.7
        OS/Arch:     linux/amd64
        Enabled:     RBAC
```
- Kubernetes version:
```
Client Version: v1.28.1
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.0
```
- Platform:

### PR DESCRIPTION
**Pull request by smira**
Fixes #7679

This should be no-op if the link name is <= 10 chars, but with predictable interface names based on MAC addresses, they have to be shortened to make some space for VLAN ID.

### CODE REVIEW

File: pkg/machinery/nethelpers/vlan.go [hunk 1]
```diff
@@ -0,0 +1,32 @@
...
+	// VLAN ID is actually 12-bit, so the allowed values are 0-4095.
+	// In ".%d" format, vlanID can be up to 5 characters long.
+	if len(base)+5 <= maxLinkNameLength {
+		return fmt.Sprintf("%s.%d", base, vlanID)
+	}
+
+	// If the base name is too long, we need to truncate it, but simply
+	// truncating might lead to ambiguous link name, so take some hash of the original
+	// name.
+	prefix := base[:4]
```
Comment (frezbo) [inline pkg/machinery/nethelpers/vlan.go:27]: is this the same way networkmanager does this?

Comment (smira) [reply pkg/machinery/nethelpers/vlan.go:27]: good question, no idea how it does that :shrug: this is what I invented

Comment (smira) [reply pkg/machinery/nethelpers/vlan.go:27]: this is the only place Talos creates an interface name itself.
