### PR TITLE
fix: ignore http proxy on grpc socket dial

### LINKED ISSUE #10867: Upgrade to 1.10 fails if http proxy is enabled
## Bug Report
Upgrade from 1.9.5 to 1.10.0 fails if http_proxy is enabled. At the moment I disabled proxy (by removing `machine.env.*proxy` configs) the upgrade went smoothly.

### Description
I used `talosctl pcap` to get more information. So we have:
Image
It is last few connections before node rebooted.

As you can see, it looks like talos installer tried to `CONNECT` to empty host, which the proxy didn't like. My uneducated guess is, that `http_proxy` setting captures request to unix socket here: https://github.com/siderolabs/talos/blob/ae87edffbcdaed12fef41541622f27882ed63755/cmd/installer/pkg/install/errata.go#L50 .

Last note - discovery is disabled in this cluster.

### Logs
```
node-w1.example.com: user: warning: [2025-05-02T11:45:04.982628355Z]: [talos] task upgrade (1/1): performing upgrade via "factory.talos.dev/vmware-installer/903b2da78f99adef03cbbd4df6714563823f63218508800751560d3bc3557e40:v1.10.0"
node-w1.example.com: user: warning: [2025-05-02T11:45:05.060518355Z]: 2025/05/02 11:45:05 running Talos installer v1.10.0
node-w1.example.com: user: warning: [2025-05-02T11:45:05.063182355Z]: 2025/05/02 11:45:05 system disk wipe on upgrade is not supported anymore, option ignored
node-w1.example.com: user: warning: [2025-05-02T11:45:05.070480355Z]: Error: error getting Talos version: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: failed to do connect handshake, response: \"HTTP/1.1 400 Bad Request\\r\\nConnection: close\\r\\nContent-Length: 1516\\r\\nContent-Type: text/html;charset=utf-8\\r\\nDate: Fri, 02 May 2025 11:45:05 GMT\\r\\nMime-Version: 1.0\\r\\nServer: squid/5.9\\r\\n<SNIP>
node-w1.example.com: user: warning: [2025-05-02T11:45:05.072876355Z]: Usage:
node-w1.example.com: user: warning: [2025-05-02T11:45:05.072926355Z]:   installer install [flags]
node-w1.example.com: user: warning: [2025-05-02T11:45:05.072993355Z]: 
node-w1.example.com: user: warning: [2025-05-02T11:45:05.073040355Z]: Flags:
node-w1.example.com: user: warning: [2025-05-02T11:45:05.073080355Z]:   -h, --help   help for install
node-w1.example.com: user: warning: [2025-05-02T11:45:05.073152355Z]: 
node-w1.example.com: user: warning: [2025-05-02T11:45:05.073183355Z]: Global Flags:
node-w1.example.com: user: warning: [2025-05-02T11:45:05.073232355Z]:       --arch string                    The target architecture (default "amd64")
node-w1.example.com: user: warning: [2025-05-02T11:45:05.073388355Z]:       --board string                   Deprecated: no op (default "none")
node-w1.example.com: user: warning: [2025-05-02T11:45:05.073516355Z]:       --bootloader                     Deprecated: no op (default true)
node-w1.example.com: user: warning: [2025-05-02T11:45:05.073641355Z]:       --config string                  The value of talos.config
node-w1.example.com: user: warning: [2025-05-02T11:45:05.073757355Z]:       --disk string                    The path to the disk to install to
node-w1.example.com: user: warning: [2025-05-02T11:45:05.073884355Z]:       --extra-kernel-arg stringArray   Extra argument to pass to the kernel
node-w1.example.com: user: warning: [2025-05-02T11:45:05.074015355Z]:       --force                          Indicates that the install should forcefully format the partition
node-w1.example.com: user: warning: [2025-05-02T11:45:05.074183355Z]:       --meta metaValueSlice            A key/value pair for META (default [])
node-w1.example.com: user: warning: [2025-05-02T11:45:05.074317355Z]:       --platform string                The value of talos.platform
node-w1.example.com: user: warning: [2025-05-02T11:45:05.074436355Z]:       --upgrade                        Indicates that the install is being performed by an upgrade
node-w1.example.com: user: warning: [2025-05-02T11:45:05.074596355Z]:       --zero                           Indicates that the install should write zeros to the disk before installing
node-w1.example.com: user: warning: [2025-05-02T11:45:05.074778355Z]: 
node-w1.example.com: user: warning: [2025-05-02T11:45:05.074810355Z]: error getting Talos version: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: failed to do connect handshake, response: \"HTTP/1.1 400 Bad Request\\r\\nConnection: close\\r\\nContent-Length: 1516\\r\\nContent-Type: text/html;charset=utf-8\\r\\nDate: Fri, 02 May 2025 11:45:05 GMT\\r\\nMime-Version: 1.0\\r\\nServer: squid/5.9\\r\\n<SNIP>
```

### Environment

- Talos version: 1.9.5 / installer 1.10.0
- Platform: vmware

### PR DESCRIPTION
**Pull request by smira**
Fixes #10867

### CODE REVIEW

**Comment by smira** [comment]
I plan to add an integration test for it as well

**Review by frezbo — APPROVED** [review]
Does this mean with new machinery we can drop the alpn env var hack or start using new grpc proxy?

**Comment by frezbo** [comment]
> Does this mean with new machinery we can drop the alpn env var hack or start using new grpc proxy?

Nevermind, this is a completely different fix

**Comment by smira** [comment]
> I plan to add an integration test for it as well

Now we have `e2e-airgapped` which tests with http proxy on to detect such regressions.

File: hack/test/e2e-qemu.sh [hunk 1]
```diff
@@ -262,6 +262,18 @@ case "${WITH_ENFORCING:-false}" in
     ;;
 esac
 
+case "${WITH_AIRGAPPED:-false}" in
+  false)
+    ;;
+  *)
+    "${TALOSCTL}" debug air-gapped --advertised-address 172.20.1.1 >/tmp/airgapped.log 2>&1 &
```
Comment (frezbo) [inline hack/test/e2e-qemu.sh:269]: we should add this to additional artifacts in kres yanl otherwise won't get uploaded

Comment (smira) [reply hack/test/e2e-qemu.sh:269]: I did

Comment (smira) [reply hack/test/e2e-qemu.sh:269]: yeah, it's saved

Comment (frezbo) [reply hack/test/e2e-qemu.sh:269]: ahh I was blind
